### ISSUE TITLE
SurvivalFly false positive with Blindness

### ISSUE THREAD

**Issue by Momonche** [Updated-NoCheatPlus/NoCheatPlus#10]
### Full output of /ncp version
---- Version information ----
#### Server ####
git-Paper-264 ~MC: 1.15.2~
detected: 1.15.2
#### NoCheatPlus ####
Plugin: 3.17-SNAPSHOT-b1153-CustomFork
MCAccess: 1.13.2-1.15|? / Bukkit-API
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | MCAccessBukkitModern
checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
defaults: pvpKnockBackVelocity
packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight
Hooks: AllViolations~NCP~ 1.0 | ViolationFrequency~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v4.5.1-SNAPSHOT-b451 | ProtocolSupport v4.29-dev

### Describe the issue
When a player have the Blindness effect, he can't move
[NC+] MissClick failed SurvivalFly: tried to move unexpectedly (VL207)

### How to reproduce the issue
Give Blindness effect on a non-OP player

**Comment by Ferocimo** [comment]
It's a huge problem on my server since we have spells that cause blindness !

**Comment by Lysandr0** [comment]
SurvivalFly will only prevent players from moving if they attempt to sprint with blindness, since it's not legit behaviour.
If you have plugins that allow players to do so, give them the following permission to bypass the check: `nocheatplus.checks.moving.survivalfly.sprinting`

**Comment by CaptainObvious0** [comment]
Just as Lysandr0 stated, its non-vanilla movement so it will flag. Add the permission node as they suggested to skip checking for sprinting while blind.

**Comment by Ferocimo** [comment]
@Lysandr0 @CaptainObvious0 I'm sorry, but that's not the issue. A blinded player cannot move at all, not just "not sprint" he is litterally petrified on the spot. On our server, nothing allows a player to sprint while blinded, and without NCP a blinded player can walk but not sprint. With NCP, he can't move at all. Did you try to reproduce it ?

**Comment by CaptainObvious0** [comment]
So adding the permission node does not fix it? Could you create a debug log and video showing the issue? Are you sure the spells are not giving the player any other abilities?

**Comment by Ferocimo** [comment]
If I understand correctly, giving them this permission will also allow them to cheat to some extent, bypassing some "sprint checking". We would like to avoid that, as we believe this clearly is an issue that should be adressed and not worked around... 
I'm going to see what I can do about that video, but you can very easily reproduce it yourself (if it's indeed a NCP issue, which we think it is). Just give the blindness effect to a player using the command /effect.
We tried that with that command so no spells were involved. Spells just happen to be the main way that players can give blindness on our server, but there are also some custom potions. Anyway whatever way you get the blindness effect, this issue will occur.

**Comment by CaptainObvious0** [comment]
Oh, I see the issue now. It is indeed an issue with NoCheatPlus itself. If you have assumesprint enabled in the config (which it is by default) it default all movements that the player is sprinting. I'll fix it now and push a commit with a fix in a moment. Sorry about the confusion. 

Fixed with 7651880

**Comment by Ferocimo** [comment]
Great, thank you very much ! We'll try the fix right away.

**Comment by Momonche** [comment]
I took 10 minutes to upload a video so I have to post it
https://www.youtube.com/watch?v=mAenhSWGjTQ

Thanks for help

**Comment by Ferocimo** [comment]
It works perfectly now, thank you.
