### ISSUE TITLE
False on chests/cocoa beans over ice/slime blocks

### ISSUE THREAD

**Issue by yorik100** [Updated-NoCheatPlus/NoCheatPlus#101]
### ![image](https://user-images.githubusercontent.com/16320315/109219215-9b1cab80-77b7-11eb-8071-552469e8d661.png)
 This setup (chests over ice/slime) and this one
![image](https://user-images.githubusercontent.com/16320315/109219248-a7a10400-77b7-11eb-921b-30fad32b5c38.png)
 (cocoa beans over ice/slime) false as heck.
Also these 2 setups false aswell (with the stair and the slimeblocks with blocks above one block out of two)
![image](https://user-images.githubusercontent.com/16320315/109219173-8cce8f80-77b7-11eb-87a9-3cc50287cf3b.png)
Also this one 
![image](https://user-images.githubusercontent.com/16320315/109219730-4463a180-77b8-11eb-8617-09c59759ecec.png)
Also this one too
![image](https://user-images.githubusercontent.com/16320315/109219865-796ff400-77b8-11eb-8442-9649654e992a.png)

**Comment by Lysandr0** [comment]
https://www.dropbox.com/s/25rp8tp64jjgbhz/ncp_test_2.mov?dl=0
https://www.dropbox.com/s/5l89iru4o4dlf66/NCP_test.mov?dl=0

Gonna leave these two videos here. I was able to only reproduce the slime issue and a minor Passable false positive with smaller cocoa beans (wrong boundingbox model, I'd assume).

(Reproduced on a clean test server with just Plib and NCP)

**Comment by yorik100** [comment]
> 
> 
> https://www.dropbox.com/s/25rp8tp64jjgbhz/ncp_test_2.mov?dl=0
> https://www.dropbox.com/s/5l89iru4o4dlf66/NCP_test.mov?dl=0
> 
> Gonna leave these two videos here. I was able to only reproduce the slime issue and a minor Passable false positive with smaller cocoa beans (wrong boundingbox model, I'd assume).
> 
> (Reproduced on a clean test server with just Plib and NCP)

Are you sure you're on 1.8? Also in the first vid you jump slower than a low-witted person

**Comment by Lysandr0** [comment]
Some changes to the bunnyhop model have been implemented since build 96. It should be much better than before, at least.
