### ISSUE TITLE
Show list of features in README

### ISSUE THREAD

**Issue by developomp** [Updated-NoCheatPlus/NoCheatPlus#105]
This anti cheat plugin has most number of users among the plugins I've seen so far, but I can't compare it with other plugins to see if it has all the fixes I need. It doesn't have any bukkit or spigot link, no list of features, no images, no nothing. Can we at lease get a list of features in the README?

**Comment by KMatias123** [comment]
there is a documentation that lists all the features

**Comment by developomp** [comment]
still doesn't change the fact that the README for this repo is a bit lacking

**Comment by xaw3ep** [comment]
You can now take a look at [Wiki](https://github.com/Updated-NoCheatPlus/Docs/blob/master/Settings/Checks/Checks.md)
