### ISSUE TITLE
No config to disable Jesus Hack.

### ISSUE THREAD

**Issue by KRYMZ0N** [Updated-NoCheatPlus/NoCheatPlus#107]
The survival fly feature patches a common hack called Jesus which allows you to walk on water. I run an anarchy server where only server damaging hacks need to be patched, and the original ncp was just that. I think a feature to disable the Jesus patch would be beneficial to Anarchy server owners that will most likely update to 1.16 when/if 2b2t does.

Basically there could be a config option called "Jesus" that allows for servers that want this hack patched to be patched, but if it's disabled it can allow the hack to work.

**Comment by Lysandr0** [comment]
You can give to your players the `nocheatplus.checks.moving.survivalfly.waterwalk` bypass permission node.
https://github.com/Updated-NoCheatPlus/Docs/blob/master/Settings/Permissions.md#specific

**Comment by KRYMZ0N** [comment]
Thank you!!

**Comment by hyperdefined** [comment]
Adding this permission doesn't fix the problem for me.

**Comment by Lerbiq** [comment]
This issue should be reopened. The permission allows players to walk only a few blocks. After that NCP will rubberband them and basically force them to turn off jesus if they want to move.

**Comment by Lysandr0** [comment]
Nothing about permissions has changed with recent commits.
Could you please provide a video with waterwalk off and simply moving on calm water surface (with granted permission)? Just to confirm a suspicion I've had for a bit (false positive... :) ).

**Comment by Lerbiq** [comment]
In the end I figured it out. Having waterwalk permission set to true and manipulating the voxel shapes is simply not enough. But it's possible to use jesus with waterwalk on. I can send the code if needed.

**Comment by compieter-gh** [comment]
anyway too fix this?
