### ISSUE TITLE
No slow problems while eating

### ISSUE THREAD

**Issue by akalpr** [Updated-NoCheatPlus/NoCheatPlus#109]
#### Server ####
git-Spigot-7754231-94b0980 ~MC: 1.12.2~
#### NoCheatPlus ####
Plugin: 3.17-SNAPSHOT-Updated-b93
MCAccess: 1.12-1.12.2 / Spigot-CB-1.12_R1
checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight

### Describe the issue
I cant eat an egap or anything else while a no slow cheat is active.
It jsut try and stop right after.

### How to reproduce the issue
Turn on no slow module in your cheat client.

### Extra links/Videos (Including debug logs)
https://www.youtube.com/watch?v=MB_-O34fRV8

**Comment by akalpr** [comment]
Update : 
After setting reset-activeitem to true 
I can eat gapples while Noslow active, but while I eat, it freeze me, and when the eating process is over, the char start moving again. 

Any Ideas ? 

Thanks

**Comment by Lysandr0** [comment]
Possibly fixed by the latest commit (build 130)
