### ISSUE TITLE
Sword Block and Null Message 

### ISSUE THREAD

**Issue by KaguraMatsuri** [Updated-NoCheatPlus/NoCheatPlus#115]
When players in 1.8.9 use Sword Block, the NCP often keeps them in the Block state, but the player client thinks that they have not done so, which will lead the NCP to suspect that the player has used "NCP: [15:33:35] player.survivalfly VL 3169"

When some clients turn on Criti to cheat, NCP will always send blank messages to everyone. (I am sure I am using the latest version of NCP)

**Comment by xaw3ep** [comment]
Please provide information using /ncp version
