### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by MrXiaoM** [Updated-NoCheatPlus/NoCheatPlus#116]
Cool job, bro. I want to share your Updated-NoCheatPlus with Chinese Minecraft players so that they can also benefit from it. Would you mind if I reprint it to the [mcbbs](https://www.mcbbs.net/)? I will indicate the address of this repository in the post. Thanks in advance.

I have been send the [post](https://www.mcbbs.net/forum.php?mod=viewthread&tid=1200393). I will delete it if you want.

**Comment by xaw3ep** [comment]
No problem. I actually appreciate that
