### ISSUE TITLE
Levitation with levels > 127 not works :/

### ISSUE THREAD

**Issue by molor** [Updated-NoCheatPlus/NoCheatPlus#120]
According to minecraft wiki:

> If a player is given a levitation level over 127, they instead fall down at a fast or slow rate, depending on the value.‌

> Using /effect <player> minecraft:levitation <time in seconds> 255 makes the player fly in Survival and not jump.

But this not works with NCP. Try it in singleplayer and on server with NCP.

**Comment by Lysandr0** [comment]
Should be fixed with latest commit.
