### ISSUE TITLE
1.17 support?

### ISSUE THREAD

**Issue by DimitarSamarov07** [Updated-NoCheatPlus/NoCheatPlus#123]
Will that happen and is there an ETA?

**Comment by MarkElf** [comment]
1.17 support when? Pl0x work harder devs -_-

**Comment by ghost** [comment]
Yes this would be nice

**Comment by Imptovskii** [comment]
It would not hurt, the players already want 1.17. And I have anarchy server, and I would like to support 1.17. Updated NCP has proven itself very well

**Comment by MarkElf** [comment]
NCP 1.17 when?

**Comment by molor** [comment]
1.17.1 will be released soon, but we are still trying to wake up the developer to update the plugin to at least 1.17 /:

**Comment by MarkElf** [comment]
Yes, the developer needs to update right meow before 1.17.1. We all can't contribute anything at all to the project but that's ok, we can keep commenting about how we wish someone else will do it instead. It'll happen eventually. /s

**Comment by Romvnly-Gaming** [comment]
I'm not sure why you guys even ask for a ETA, no sane developer will give you one. 🤣

**Comment by DimitarSamarov07** [comment]
> I'm not sure why you guys even ask for a ETA, no sane developer will give you one. 🤣

A "We are working on it and there's no ETA" from the main dev would be enough. Pretty sure that we are all asking for confirmation that this is being worked on(which I am kinda starting to doubt)

**Comment by Romvnly-Gaming** [comment]
We’ll see! 😅

**Comment by xaw3ep** [comment]
Completed in b108
