### ISSUE TITLE
1.17 Data-pack worlds is unsupported

### ISSUE THREAD

**Issue by Stabrinai** [Updated-NoCheatPlus/NoCheatPlus#129]
### Full output of /ncp version
?Version information?
Server:
git-Paper-119 ~MC: 1.17.1~
Detected: 1.17.1
NoCheatPlus:
Plugin: 3.17-SNAPSHOT-Updated-b101
MCAccess: 1.13-1.17|? / Bukkit-API
Features:
blocks: BlocksMC1_4, BlocksMC1_5, BlocksMC1_6_1, BlocksMC1_7_2, BlocksMC1_8, BlocksMC1_9, BlocksMC1_10, BlocksMC1_11, BlocksMC1_12, BlocksMC1_13, BlocksMC1_14, BlocksMC1_15, BlocksMC1_16, BlocksMC1_17, MCAccessBukkitModern
checks: FastConsume, Gutenberg, HotFixFallingBlockPortalEnter, AttackFrequency, FlyingFrequency, KeepAliveFrequency
defaults: pvpKnockBackVelocity
packet-listeners: UseEntityAdapter, MovingFlying, OutgoingPosition, KeepAliveAdapter, SoundDistance, WrongTurnAdapter, NoSlow, Fight
Hooks:
AllViolations~NCP~ 1.0, ViolationFrequency~NCP~ 1.0
?Related Plugins?
ProtocolLib v4.7.1-SNAPSHOT-b102

### Describe the issue
Entering negative Y will be judged as SurvivalFly

### How to reproduce the issue
No

**Comment by xaw3ep** [comment]
What do you mean "correct judgments" anyway? 
Are you trying to say that standing on blocks in negative Y causing massive false positives?

**Comment by Stabrinai** [comment]
> What do you mean "correct judgments" anyway?
> Are you trying to say that standing on blocks in negative Y causing massive false positives?

Yes, Sorry for my english,
Players who enter a negative Y will bounce all the time, are judged as SurvivalFly.
After entering negative Y, the block under negative Y cannot be mined, and it is judged as FastBreak.
Disable SurvivalFly detection and FastBreak detection and return to normal.

**Comment by MarkElf** [comment]
Anything below 0 is void in vanilla and NCP enforces that. Someone posted a similar issue either on here or on the discord. I'm not sure how far we got with that but it's worth exploring. I feel like this is something NCP is going to need to adjust to anyway as I believe 1.18 will allow players to go below 0 (at least in previously generated worlds) if I'm not wrong.

This section might be the most that you can tweak on your own.
      setbackpolicy:
        falldamage: true
        voidtovoid: false

**Comment by xaw3ep** [comment]
Can now adjust on b102 with config path `compatibility.blocks.blockcache.minimalworldy` . Should be near the bottom of the config. Change it to the negative y that data-pack expand, for example -30.
