### ISSUE TITLE
SurvivalFly check is too strict.

### ISSUE THREAD

**Issue by dovidas147** [Updated-NoCheatPlus/NoCheatPlus#13]
### Full output of /ncp version
https://i.imgur.com/C8MZ3DD.png
### Describe the issue
Whenever people jump and get shot by projectile in mid air, they're pulled down to ground and flagged as survivalfly.
### How to reproduce the issue
Place a dispenser and add arrows to it, make a redstone clock and try to get hit in midair. Or get some people to shoot at you.
### Extra links/Videos (Including debug logs)
Proof 1:
https://streamable.com/qr2lpn
Proof 2:
https://streamable.com/v38p6m
NCP logs:
https://anonfiles.com/ddc0Adxeo9/nocheatplus_log
### Any possible config options changed or plugins that may cause interference?
I'm using custom made NCP config. But it doesn't matter because even without it it persists.

**Comment by CaptainObvious0** [comment]
I'm unable to reproduce the issue described. Do you have any plugins that modify knockback? Have you changed the value `disable-relative-projectile-velocity` in the paper spigot configuration?

Your debug log is missing information. You will need to do `/ncp debug player (player)`, reproduce the issue, and then post that log here.

Some things you could play around with are the velocity settings in the configuration. Try lowering/raising the values here:
`    velocity:
      activationcounter: 80
      activationticks: 140
      strictinvalidation: true`

**Comment by dovidas147** [comment]
fork of spigot  (imanitySpigot) modifies knockback. Maybe that's the case?

**Comment by dovidas147** [comment]
That was my custom knockback issue. I changed it and it works now. Thank you for your 200IQ thinking. Closed

**Comment by CaptainObvious0** [comment]
Yes, if you're changing how velocity works then you will see flags. By default NoCheatPlus will handle velocity as if it's untouched, so it doesn't know how to handle when velocity has been modified.

The only recommendation I would suggest is playing around with the config options I suggested. First try lowering activationcounter and see how that works out.
