### ISSUE TITLE
Patch on-ground boatfly/entity speed or reduce max speed

### ISSUE THREAD

**Issue by deciduous-buffalo** [Updated-NoCheatPlus/NoCheatPlus#134]
Currently on-ground boatfly and entity speed work at a max speed of around 18-19 blocks per second before it starts to dismount/lag you back. I understand that patching these two entirely without introducing new false positives may be very difficult, but is there any way you can lower the max speed to something reasonable, like 10 blocks per second? Or allow this to be configurable

Thanks

**Comment by Imptovskii** [comment]
Try to do this. But roads made of ice will not work.

![image](https://user-images.githubusercontent.com/82046704/127303846-59e826f0-9d1f-4070-865a-8e346fbeec38.png)

**Comment by deciduous-buffalo** [comment]
Works great Imptovskii, thanks
