### ISSUE TITLE
Make Timer checks more strict

### ISSUE THREAD

**Issue by deciduous-buffalo** [Updated-NoCheatPlus/NoCheatPlus#136]
Currently when using Timer at 1.2 it allows the player to move at that speed for like 8 seconds before it starts lagging you back in place, and at 1.4-1.5 you can still use it in short 2-3 second bursts. Is there a way to change the default config to make it more strict?

**Comment by Lysandr0** [comment]
Might be useful :p 
https://github.com/Updated-NoCheatPlus/Docs/blob/master/Settings/Checks/%5BMoving%5D-Morepackets.md
https://github.com/Updated-NoCheatPlus/Docs/blob/master/Settings/Checks/%5BNet%5D-Flyingfrequency.md

**Comment by deciduous-buffalo** [comment]
I was able to improve the strictness of it but its still far from my liking, if anyone reading this has a good config they can share me for their Morepackets and FlyingFrequency please do, I'd appreciate it

**Comment by Lysandr0** [comment]
https://github.com/Updated-NoCheatPlus/NoCheatPlus/commit/a684a107f0ab3353c93fe893e9cf56b18f84b026#diff-e13bc6d760e2af7842a590792ebb501aaf9438bd4e14a2e5a6d141c61443183dR520

Attempted to make it more strict. From testings, these settings seem to pick up 1.1 timers and the like decently well. Theoretically, you could make it even stricter with `monitored seconds: 3` / `epsmax: 21` and `setbackage: 250`; I wouldn't recommend it however as it will be extremely harsh to laggy players, especially with setbackage being this high.

(Likely a rework of MorePackets will be more appropriate, possibly merging it with FlyingFrequency...)

**Comment by deciduous-buffalo** [comment]
These changes work great, even picks up 1.05 decently. Thanks Lysandre

**Comment by Lysandr0** [comment]
Closing as resolved then. :)
