### ISSUE TITLE
NoFall false positive on vines

### ISSUE THREAD

**Issue by JimusHimus** [Updated-NoCheatPlus/NoCheatPlus#14]
![изображение](https://user-images.githubusercontent.com/39002687/81483193-04412b80-9245-11ea-9b9f-6f0d55cd786d.png)

When a player presses the space when go down on vines with elytra he get not significant but false positive NoFall

Reproduce:
Get up on vines, move back a little, press space

Log:
[nocheatplus.log](https://github.com/Updated-NoCheatPlus/NoCheatPlus/files/4604372/nocheatplus.log)
![изображение](https://user-images.githubusercontent.com/39002687/81483359-4ae35580-9246-11ea-8a23-4e1a0de41416.png)

Video on discord:
https://discordapp.com/channels/598285007496151098/603221572890656807/708599131370946621

**Comment by CaptainObvious0** [comment]
Issue fixed with commit 72f26af
