### ISSUE TITLE
NPE: cannot invoke "fr.neatmonster.nocheatplus.utilities.map.BlockCache.getOrCreateBlockCacheNode(int, int, int, boolean)" because "this.blockCache" is null

### ISSUE THREAD

**Issue by Lysandr0** [Updated-NoCheatPlus/NoCheatPlus#142]
### Full output of /ncp version
(Check log)

### Describe the issue
Don't know how to reproduce it unfortunately. It randomly appeared in console.

### Extra links/Videos (Including debug logs)
https://pastebin.com/3gT5RSJF

### Any possible config options changed or plugins that may cause interference?
Default config.

**Comment by xaw3ep** [comment]
Might want to be careful with shouldCheckSurvivalFly call without to location set:
https://github.com/Updated-NoCheatPlus/NoCheatPlus/blob/master/NCPCore/src/main/java/fr/neatmonster/nocheatplus/checks/moving/MovingListener.java#L2314

https://github.com/Updated-NoCheatPlus/NoCheatPlus/blob/master/NCPCore/src/main/java/fr/neatmonster/nocheatplus/checks/fight/Critical.java#L127

**Comment by Lysandr0** [comment]
Yeah, sorry for the inconvenience, totally overlooked it.
