### ISSUE TITLE
Bungeecord Support

### ISSUE THREAD

**Issue by ghost** [Updated-NoCheatPlus/NoCheatPlus#143]
### Describe the features of this added check
Not a check, just support for bungee cord notifications and syncing, also being able to (for example) ban players on one of your bungee cord servers while you are on another
### Description of how this check would work
Just showing and syncing detections to all servers and specifying what server, also being to target the command at a certain server or it automatically executing that server without having to switch.

**Comment by Phoenix616** [comment]
For notifications there are plugins that do that, I have [a fork](https://github.com/Phoenix616/BungeeNCPNotify/) of one that I updated a while ago (and so [does Brokko](https://github.com/Brokkonaut/BungeeNCPNotify)) which probably still works.
