### ISSUE TITLE
How to allow jesus (waterwalk) on a horse?

### ISSUE THREAD

**Issue by compieter-gh** [Updated-NoCheatPlus/NoCheatPlus#156]
### Describe the issue
Well i an have jesus (waterwalk) bypassed with a permission but doesn't work on animals.

### How to reproduce the issue
Bypass the waterwalk and ride an animal

### Extra links: video and/or debug log
https://youtu.be/6YFwtde2N8E

### Any possible config options changed or plugins that may cause interference?
Unsure

**Comment by Lysandr0** [comment]
Vehicle.envelope doesn't check for waterwalk permission, for now. :p
