### ISSUE TITLE
[BUG] survival fly with stairs and water

### ISSUE THREAD

**Issue by SkyDude0** [Updated-NoCheatPlus/NoCheatPlus#160]
Version: 1.16.5 tuinity , NPC version: b117

ISSUE:
Spamming survivalfly check when someone try to climb the stairs with the water as shown in the picture

TO REPRODUCE:
try to climb stairs with water

EXAMPLE: 
![2021-09-16_06 48 53](https://user-images.githubusercontent.com/85011614/133551580-3464217d-8d66-4760-bc83-98998276e7f5.png)

**Comment by Lysandr0** [comment]
Just to clarify:
- On what version is the client in question (I see you're running ViaVersion)?
- What are the subchecks/tags displayed when triggering SurvivalFly?
- From the screenshot, the player seems to be exposed to potion effects, do they happen to have the jump one?

**Comment by SkyDude0** [comment]
- my server is 1.16.5
- yes i use via version
- client is 1.16.5
- it happend even without potion
- subchecks is: hstairs+liquidground

**Comment by Lysandr0** [comment]
Build 118 should address this. I currently lack the time to test anything however, so do leave a note if it doesn't.

**Comment by SkyDude0** [comment]
ill do some test and it work for now! thanks
