### ISSUE TITLE
Killing players when they enter below y=0

### ISSUE THREAD

**Issue by TheMikol** [Updated-NoCheatPlus/NoCheatPlus#168]
**I am using datapack 1.18, where the world starts from y-64 level. Players when they enter below level 0 are killed after a while or when they return back to level 0 they are killed. I have not changed anything in the settings.**

**Comment by Lysandr0** [comment]
Try altering the `minimalworldY` setting to `-64` under the compatibility section
https://github.com/Updated-NoCheatPlus/Docs/blob/9e6ffd36a9a739f75b1b0f3209b1bf2fabebabc4/Settings/%5BSettings%5D-Compatibility.md

**Comment by TheMikol** [comment]
Ooo, now it works, thank you for your help!
