### ISSUE TITLE
SurivalFly false positive with honey block elevator

### ISSUE THREAD

**Issue by wolf0023** [Updated-NoCheatPlus/NoCheatPlus#169]
### Full output of /ncp version
[Server thread/INFO]: ╗Version information½
[Server thread/INFO]: Server:
[Server thread/INFO]: 3094-Spigot-9fb885e-fae895a ~MC: 1.16.5~
[Server thread/INFO]: Detected: 1.16.5
[Server thread/INFO]: NoCheatPlus:
[Server thread/INFO]: Plugin: 3.17-SNAPSHOT-Updated-b114
[Server thread/INFO]: MCAccess: 1.13-1.17|? / Bukkit-API
[Server thread/INFO]: Features:
[Server thread/INFO]: blocks: BlocksMC1_4, BlocksMC1_5, BlocksMC1_6_1, BlocksMC1_7_2, BlocksMC1_8, BlocksMC1_9, BlocksMC1_10, BlocksMC1_11, BlocksMC1_12, BlocksMC1_13, BlocksMC1_14, BlocksMC1_15, BlocksMC1_16, MCAccessBukkitModern
[Server thread/INFO]: checks: FastConsume, Gutenberg, HotFixFallingBlockPortalEnter, AttackFrequency
[Server thread/INFO]: defaults: pvpKnockBackVelocity
[Server thread/INFO]: packet-listeners: UseEntityAdapter, KeepAliveAdapter, NoSlow, Fight
[Server thread/INFO]: Hooks:
[Server thread/INFO]: AllViolations~NCP~ 1.0, Citizens2~cncp~ 2.0
[Server thread/INFO]: ╗Related Plugins½
[Server thread/INFO]: CompatNoCheatPlus v6.6.7-SNAPSHOT-2021_02_28-16_22, ProtocolLib v4.6.1-SNAPSHOT-b505, ViaVersion v4.0.1
### Describe the issue
NoCheatPlus detects players as SurvivalFly like the video when players use honey block elevator
Video: https://youtu.be/iE3IqnJhih8
### How to reproduce the issue
Please watch the video above and try it!

**Comment by Lysandr0** [comment]
Might have been fixed with the new bubble columns handling. Will need to check/test.

**Comment by Lysandr0** [comment]
Assume fixe/superseded by updates. Do leave a note if otherwise.

**Comment by wolf0023** [comment]
I checked with latest NoCheatPlus, but NoCheatPlus still detected players as SurvivalFly.
