### ISSUE TITLE
CustomJumppad pushing back

### ISSUE THREAD

**Issue by bobhenl** [Updated-NoCheatPlus/NoCheatPlus#17]
### Describe the features of this added check
Hi, when I use CustomJumppads (https://www.spigotmc.org/resources/custom-jumppads-1-8-1-15.44876/) and your plugin NoCheatPlus, it pushes players back at the end of trail (jump). So it didn't work so smooth as it should. + when you're having elytra, it's worse...

### Description of how this check would work
It should be smooth and shouldn't push players back.

**Comment by CaptainObvious0** [comment]
You will need to talk to that plugin author in order to add compatibility for NoCheatPlus. NoCheatPlus has no way of knowing when the plugin changes the player velocitys, so it will assume they are cheating. Therefore the plugin will need to hook into NoCheatPlus.
