### ISSUE TITLE
1.18.1 support?

### ISSUE THREAD

**Issue by molor** [Updated-NoCheatPlus/NoCheatPlus#181]
Just in case no one noticed there that 1.18.1 was came out.

```
[NoCheatPlus] Packet level access via ProtocolLib not available, supported configurations:  | ProtocolLib 4.7.0 or later for Minecraft 1.17.x | ProtocolLib 4.6.0 or later for Minecraft 1.16.x | ProtocolLib 4.5.0 or later for Minecraft 1.14.x to 1.15.x | ProtocolLib 4.4.0 or later for Minecraft 1.13.x | ProtocolLib 4.3.0 or later for Minecraft 1.12.x | ProtocolLib 4.2.0 or later for Minecraft 1.11.x | ProtocolLib 4.1 or later for Minecraft 1.8.x to 1.10.x | ProtocolLib 3.7.0 for Minecraft 1.7.x and earlier | ProtocolLib 3.6.6 for PaperSpigot 1.8.x
```

**Comment by Brokkonaut** [comment]
There are many false positives in 1.18, at least when mining below zero: https://cpaste.de/kopiqaqayo.yaml

**Comment by MarkElf** [comment]
> There are many false positives in 1.18, at least when mining below zero: https://cpaste.de/kopiqaqayo.yaml

This was accounted for already, just needs to be changed in the config.
  blocks:
    blockcache:
      minimalworldy: 0
> Just in case no one noticed there that 1.18 was came out.

Oh thanks, None of us noticed /s.
Why don't you contribute towards 1.18 development as you seem to be ahead of the curve on this.

**Comment by molor** [comment]
@MarkElf, I didn't mean to say that you should drop everything and quickly make a finished plugin for free. I just wanted to notify. 

Many thanks to the NCP development team for developing it!

**Comment by SlimeDog** [comment]
> This was accounted for already, just needs to be changed in the config. blocks: blockcache: minimalworldy: 0

Should `blocks.blockcache.minimalworldy: 0` be changed to -64 ? Is there a commented canonical config.yml posted anywhere?

**Comment by Lysandr0** [comment]
Should be good.
Doesn't seem like this update added any new block (At least from what appears from the wiki, besides the texture changes).
Do leave a note if otherwise.

**Comment by molor** [comment]
You are the best dev in the world, very many thanks!
