### ISSUE TITLE
Players can't breack blocks of itemsadder plugin 

### ISSUE THREAD

**Issue by SNokerYT** [Updated-NoCheatPlus/NoCheatPlus#187]
[NoCheatPlus] Version 3.17-SNAPSHOT-Updated-b127

Players can't break breack of itemsadder plugin only works with op
VIDEO | https://imgur.com/a/XK5bAZQ

**Comment by MarkElf** [comment]
Not a NCP issue. Use the blockoverwrite section,

https://github.com/Updated-NoCheatPlus/Docs/blob/master/Settings/%5BSettings%5D-Compatibility.md

**Comment by Lysandr0** [comment]
Indeed, that's not a vanilla block, so NCP doesn't know how it should interpret the shape and breaking time.
You have to either: a) manually specify the block (shape+breaking time) by looking up the compatibility section linked by Mark or b) request the developer of the plugin in question to add a hook to NCP.
