### ISSUE TITLE
Exempting a player from checks should permanently exempt them

### ISSUE THREAD

**Issue by lolleap** [Updated-NoCheatPlus/NoCheatPlus#192]
When I exempt a player from checks it only lasts until they log out. 
When they join the server again it resets the exemptions so they are no longer exempt. 
I need to exempt my friend because he has really bad connection to the server and it flags up any anticheat I have tried.

**Comment by ghost** [comment]
(make this optional if done)

**Comment by Lysandr0** [comment]
Intended behaviour, @asofold's implementation of the exemption command is meant for short-term. 
If you wish to permanently exempt a player from checks, you'll need to give them appropriate permission. Have a look at the wiki/docs for further info.

Regardless, we currently don't have any active developer working on NCP, so it wouldn't be added anyway. Not now at least. :p
