### ISSUE TITLE
Critical issue above Y zero level 1.18+

### ISSUE THREAD

**Issue by TheForgTN** [Updated-NoCheatPlus/NoCheatPlus#201]
Basicly you get stuck and flagged constantly by the anticheat below Y zero. 1.18+

**Comment by blockswerker** [comment]
I had this issue but renaming my config.yml file, restarting and updating the default settings fixed it - not a small effort for my server, but successful. Have you tried that?

If you're using Via Version or ProtocolSupport for older client support then you'll find that any clients older than 1.17 are completely unusable below y0 and players will get stuck until they fly out or switch to a newer client.

**Comment by Lysandr0** [comment]
Set the `minimalworldy` setting to `-64`, under the `blockcache` option (bottom part of the config file, compatibility section).
If your config doesn't have it, either regenerate it or add it manually. 
https://github.com/Updated-NoCheatPlus/Docs/blob/master/Settings/%5BSettings%5D-Compatibility.md

**Comment by TheForgTN** [comment]
Okay, thank you!
