### ISSUE TITLE
This anticheat doesnt work with Geysermc

### ISSUE THREAD

**Issue by danielboos1** [Updated-NoCheatPlus/NoCheatPlus#203]
### Describe the features of this added check
Add support to geysermc throught the floodgate api
### Description of how this check would work
Disable checks for the people joined through bedrock
### Any extra information about what should be added? (Config options...)
Nope

**Comment by Lysandr0** [comment]
Partial compatibility can be achieved with CompatNoCheatPlus.
The current add-on will simply exempt bedrock players (full support is planned, see comment in #205)
