### ISSUE TITLE
Berries and fail survival fly

### ISSUE THREAD

**Issue by TeoSaloufardos** [Updated-NoCheatPlus/NoCheatPlus#207]
Greetings ,I have an issue , sometimes while players jumping in berries they got stuck in there and they can't move. I will send a video link to see what happened , thanks for your time <3

link : https://youtu.be/lVVADYGb_C4

<img width="490" alt="version" src="https://user-images.githubusercontent.com/103040116/168402463-589f6a82-fefb-4c36-83ba-0e292171a8df.png">

**Comment by Lysandr0** [comment]
Will need:
- A debug log of the player
- The client's version used in the video
- If possible, a plugin list.

I will say however that the violation history shown in the video does raise some suspicions. Especially the 24 `against` violations: unless there's a bug with the check, it should be impossible to trigger legitimately. 
Achieving a 15-blocks reach is also unlikely, unless there's a plugin incompatibility of some sort involved.

**Comment by Lysandr0** [comment]
Berry bushes (among some other blocks) handling has been partly refactored in the hSpeed branch.
Assuming superseded.
