### ISSUE TITLE
Sweeping on skeletons is kicking players.

### ISSUE THREAD

**Issue by IntelligentVoid** [Updated-NoCheatPlus/NoCheatPlus#211]
### Full output of /ncp version
»Version information«
 Server:
git-Paper-372 ~MC: 1.18.2~
Detected: 1.18.2
NoCheatPlus:
Plugin: 3.17-SNAPSHOT-Updated-b140
MCAccess: 1.13-1.18|? / Bukkit-API
Features:
blocks: BlocksMC1_4, BlocksMC1_5, BlocksMC1_6_1, BlocksMC1_7_2, BlocksMC1_8, BlocksMC1_9, BlocksMC1_10, BlocksMC1_11, BlocksMC1_12, BlocksMC1_13, BlocksMC1_14, BlocksMC1_15, BlocksMC1_16, BlocksMC1_17, MCAccessBukkitModern
checks: FastConsume, Gutenberg, HotFixFallingBlockPortalEnter
defaults: pvpKnockBackVelocity
Hooks:
AllViolations~NCP~ 1.0, ViolationFrequency~NCP~ 1.0
»Related Plugins«
ViaVersion v4.3.2-SNAPSHOT
### Describe the issue
When a player attempts to hit a large group of skeletons in a 1 block area with a sweeping 3 sword, the server kicks them for "[player] failed Speed: tried to click [large number] times over the established 25 cps limit. (VL[same number as large number])
### How to reproduce the issue
Have the max amount of skeletons in a 1x1 hole, max amount = number right under entity cram limit, then attempt to hit the skeletons with a sweeping 3 sword.
### Extra links: video and/or debug log (instructions: https://github.com/Updated-NoCheatPlus/Docs/blob/master/Development/Debugging.md#on-the-fly-debug-output-for-individual-players)
https://streamable.com/5ipjxe
### Any possible config options changed or plugins that may cause interference?
Just changed 15 cps cap to 25 cps cap to see if it would fix it.

**Comment by Lysandr0** [comment]
Fight.Speed is likely going to be removed with the next update.
We already have AttackFrequency to monitor click-speed; does that throw false positives too?

**Comment by Lysandr0** [comment]
Assuming fixed, as fight.speed has been removed with commit https://github.com/Updated-NoCheatPlus/NoCheatPlus/commit/d5d16d3db5e95c75e73d2b8e733be76c4b4bf8c6
WIll be merged in master once everything is complete.
