### ISSUE TITLE
1.5 support (fix maven repo)

### ISSUE THREAD

**Issue by primitt** [Updated-NoCheatPlus/NoCheatPlus#218]
### Full output of /ncp version
22:38:21 [INFO] »Version information«
22:38:21 [INFO] Server:
22:38:21 [INFO] git-Bukkit-1.5.2-R1.0-b2788jnks ~MC: 1.5.2~
22:38:21 [INFO] Detected: 1.5.2
22:38:21 [INFO] NoCheatPlus:
22:38:21 [INFO] Plugin: 3.17.1-SNAPSHOT-Updated-b142
22:38:21 [INFO] MCAccess: 1.5-1.12.2|? / CB-Reflect
22:38:21 [INFO] Features:
22:38:21 [INFO] blocks: BlocksMC1_4, BlocksMC1_5, MCAccessCBReflect
22:38:21 [INFO] checks: FastConsume, Gutenberg
22:38:21 [INFO] defaults: enforceLocation, storePlayers
22:38:21 [INFO] Hooks:
AllViolations~NCP~ 1.0, ViolationFrequency~NCP~ 1.0

### Describe the issue
When going up stairs, nocheatplus falsely flags it as survival fly
### How to reproduce the issue
Install NCP on a eaglercraft server and thats basically it

### Any possible config options changed or plugins that may cause interference?
I havent changed any configs, but when trying to up the VL, it still doesnt work.

**Comment by Lysandr0** [comment]
Likely (if not for sure) due to the CB-reflection mode, since the native module is still missing.
In any case, it really does seem like we'll have to somewhat support 1.5 as well...

**Comment by xaw3ep** [comment]
Leaving NCP to use CB-Reflect from 1.5-1.6.4 is fine, it should work as well as the native modules.
Back to the main issue, I can't reproduce any problems with stairs. A video and debug log might be a great help!
