### ISSUE TITLE
(1.8) vDistRel leaving water false positive (possibly tied to removed workarounds)

### ISSUE THREAD

**Issue by ghost** [Updated-NoCheatPlus/NoCheatPlus#219]
Hello dear developer. I recorded a video where I haven't quite figured out the commands yet, but I still haven't gotten the debug to the fly, some message was sent to me when I opened the inventory and with each click on the slot a message was sent to me. I attached the log file, there are logs and before the recording, but other than this video, I did not do anything. Video: https://youtu.be/kkHZNPVMj1U

This not my video and error.But on 1.12.2 this fale flag me too. Version: [Updated-NoCheatPlus #143](https://ci.codemc.io/job/Updated-NoCheatPlus/job/Updated-NoCheatPlus/143/) 

Log: https://discord.com/channels/598285007496151098/603221572890656807/998841012548018276

**Comment by Lysandr0** [comment]
Is this fixed with build n.145?
(Should be, courtesy of @xaw3ep)
