### ISSUE TITLE
Add speed slowhop2 check

### ISSUE THREAD

**Issue by rejomy** [Updated-NoCheatPlus/NoCheatPlus#221]
In the cheat flux b13 works Speed slowhop2, he has no advantage when running forward, but thanks to him, you can jump backwards with the same speed as forward, the same applies to jumping sideways. It works similarly to the Strafe module (in all directions)

Log:
[nocheatplus.log](https://github.com/Updated-NoCheatPlus/NoCheatPlus/files/9228660/nocheatplus.log)
Video:  https://www.youtube.com/watch?v=-QGUaB_YUkE

**Comment by Lysandr0** [comment]
NoCheatPlus does not have checks to monitor the 3d/2d space (strafing).
They'll be added at a later time with the hSpeed rework (See ticket #197), though there are some technical limits which may delay this further (PlayerMoveEvent thresholds, split moves...)
