### ISSUE TITLE
Fall damage: Bottom slab with water source block not recognized as safe fall

### ISSUE THREAD

**Issue by NullCase** [Updated-NoCheatPlus/NoCheatPlus#23]
It seems like there's an easy config fix for this, but I don't know what it is. Still, just in case it's something you want I found some non-vanilla behavior that can result in player deaths.

### Full output of /ncp version
```
27.05 21:16:12 [Server] INFO #### Server ####
27.05 21:16:12 [Server] INFO git-Paper-284 ~MC: 1.15.2~
27.05 21:16:12 [Server] INFO detected: 1.15.2
27.05 21:16:12 [Server] INFO #### NoCheatPlus ####
27.05 21:16:12 [Server] INFO Plugin: 3.17-SNAPSHOT-b1153-CustomFork
27.05 21:16:12 [Server] INFO MCAccess: 1.13.2-1.15|? / Bukkit-API
27.05 21:16:12 [Server] INFO Features:
27.05 21:16:12 [Server] INFO blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | MCAccessBukkitModern
27.05 21:16:12 [Server] INFO checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
27.05 21:16:12 [Server] INFO defaults: pvpKnockBackVelocity
27.05 21:16:12 [Server] INFO packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | NoSlow
27.05 21:16:12 [Server] INFO Hooks: AllViolations~NCP~ 1.0 | ViolationFrequency~NCP~ 1.0
27.05 21:16:12 [Server] INFO #### Related Plugins ####
27.05 21:16:12 [Server] INFO ProtocolLib v4.5.1-SNAPSHOT-b451
```
### Describe the issue
Fall damage incorrectly applied when falling on a source block with bottom slab. Non-vanilla behavior.

### How to reproduce the issue

- Place Slab on bottom side of block
- Place water source in same block
- Jump on slab from >5 blocks
- Observe damage.
- Remove NCP, repeat.

![2020-05-28_00 17 39](https://user-images.githubusercontent.com/32785664/83098447-a734da80-a078-11ea-8e33-51e060ee025d.png)

**Comment by Lysandr0** [comment]
Likely superseded by the waterlogged blocks re-work some time ago (they are considered as liquid, thus NoFall won't apply fall damage to players)
