### ISSUE TITLE
BYPASS PACKETFLY

### ISSUE THREAD

**Issue by ghost** [Updated-NoCheatPlus/NoCheatPlus#233]
Client: https://github.com/Zane2b2t/Pyro-2.0-cracked/releases/tag/v2.1.1 

PACKETFLY BYPASS

https://user-images.githubusercontent.com/108226177/185427632-08ce0658-a93b-43cc-b7f5-5740c2e3b9bf.mp4

**Comment by Lysandr0** [comment]
Please don't clutter the tracker with duplicate tickets. You've already reported this with #231.
