### ISSUE TITLE
Increase the number of Killaura checks

### ISSUE THREAD

**Issue by rejomy** [Updated-NoCheatPlus/NoCheatPlus#236]
I propose to add more combat checks (Killaura), for example, heuristics check as in AAC3, of course, it failed there because of a lot of false positives, but... who knows, maybe it will work here. Also add high neatness checks on hits, but be sure to eliminate or mitigate actions in small rooms, on stairs, and in cobwebs. Add checks for hit timings, pre, post. Add rotation check for player, e.g. if he hits only body or head, also add yaw value check, e.g. to block random center.
### Any additional information on what should be added? (Configuration parameters...)
Here is the config of the same aac3, link - https://paste.md-5.net/ivotijukiz.php and https://paste.md-5.net/iwosowarif.bash
aac3 heuristics - https://paste.md-5.net/niyadesiqo.bash

**Comment by Lysandr0** [comment]
See ticket #235 :)
