### ISSUE TITLE
[False positive] Build under player when sneaking

### ISSUE THREAD

**Issue by Momonche** [Updated-NoCheatPlus/NoCheatPlus#24]
### Full output of /ncp version
---- Version information ----
#### Server ####
git-Paper-332 ~MC: 1.15.2~
detected: 1.15.2
#### NoCheatPlus ####
Plugin: 3.17-SNAPSHOT-b1153-CustomFork
MCAccess: 1.13.2-1.15|? / Bukkit-API
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | MCAccessBukkitModern
checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
defaults: pvpKnockBackVelocity
packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight
Hooks: AllViolations~NCP~ 1.0 | ViolationFrequency~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v4.5.1-SNAPSHOT-b451 | ProtocolSupport v4.29-dev

### Describe the issue
When a player build under him while sneaking backward (building a bridge), the block diseapear and log a false positive

### How to reproduce the issue
Build a bridge when sneaking

### Extra links/Videos (Including debug logs)
[NC+] MissClick failed Scaffold: tried to place a block in an unnatural way (Tags: Time) (VL30)

**Comment by Phoenix616** [comment]
Do you use a fresh config? If not then could you provide that? Because I'm pretty sure this was fixed for me when updating my config to the new values.

**Comment by Momonche** [comment]
That's true, thanks for info @Phoenix616
