### ISSUE TITLE
Geyser Compatibility

### ISSUE THREAD

**Issue by TeoSaloufardos** [Updated-NoCheatPlus/NoCheatPlus#240]
My server is running with geyser crossplatform plugin. As you know the NoCheatPlus anticheat has a plenty of wrong errors. One for the most annoying is SurvivalFly wrong check while someone tries to climb in vines , glow berrier and water.

I dont know exactly if NoCheatPlus is compatible with geyser but my request is to add compatibility checks for Geyser/Bedrock players.

Thanks for your time , have a nice day

**Comment by ghost** [comment]
use CompactNoCheatPlus addon

**Comment by TeoSaloufardos** [comment]
i am using it , still have a lot of problems

**Comment by Lysandr0** [comment]
Possibly related to #232.
Some actual fully-fledged checks are planned, at some distance however.
