### ISSUE TITLE
NCP fly/longjump bug

### ISSUE THREAD

**Issue by drcrypter2007** [Updated-NoCheatPlus/NoCheatPlus#255]
#### *Complete* output of the `ncp version` command (please prefer text here)
3.17.1-SNAPSHOT-Updated-b149 (but this works on any version)

#### Short description of the issue and how to reproduce (is it random / always happens / side conditions ?)
Go under a block, and right when you walk away, then set your speed to a high amount (following friction rules) and you can
go any speed you'd like. (You can also go really high up)
@CaptainObvious0 has already patched this on Hypixel's Watchdog a few days ago, but he didn't fix it here.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
No.

#### Do you run any other special plugins that affect game mechanics next to NC+ (skills, machines, adding/changing blocks, other anti-cheating)?
No.

#### Provide additional information: for bypasses, vulnerabilities and reproducible issues, we request a [debug log. ](https://github.com/Updated-NoCheatPlus/Docs/blob/master/Development/Debugging.md#on-the-fly-debug-output-for-individual-players) Use [GitHub gists](https://gist.github.com/) or [PasteBin](http://pastebin.com/) or similar for errors and huge logs, or attach a (zip-) file here.

https://www.youtube.com/watch?v=xKUN-zqG5Cg
Here is a video of it in action. Reproduce it yourself by doing what I said.

**Comment by Lysandr0** [comment]
Does it look any better with build 151?

**Comment by drcrypter2007** [comment]
On my local test server running the latest build (3.17.1-SNAPSHOT-Updated-b151) it seems to have been fixed (even with smaller values).

**Comment by Lysandr0** [comment]
Thank you for the quick response.

**Comment by Spinyfish** [comment]
Can confirm BlocksMC loves this issue.
