### ISSUE TITLE
Edit config to fix bypass.

### ISSUE THREAD

**Issue by ghost** [Updated-NoCheatPlus/NoCheatPlus#258]
For fix packetfly made this: 

    moving: (netmoving check)
      active: default
      actions: cancel vl>15 cancel cmdc:kickpacketfrequency

**Comment by Lysandr0** [comment]
The default config already cancels illegal movements.
We can't kick the player as of now due to a couple of false positives which will need to be taken care of first.

**Comment by ghost** [comment]
> The default config already cancels illegal movements. We can't kick the player as of now due to a couple of false positives which will need to be taken care of first.

yes this cancel but not 100% cancel, i can fly slow
