### ISSUE TITLE
Let survivalfly check support KbMaster 2.15.0

### ISSUE THREAD

**Issue by FengXiaoSkidGod** [Updated-NoCheatPlus/NoCheatPlus#260]
### Describe the features of this added check
emmm,Make NCP support custom player kb
### Description of how this check would work
1:Maybe the problem of survuvalfly detecting that kbmaster is not supported can be solved by adjusting the size of kb in config?
2:support custom kb
### Any extra information about what should be added? (Config options...)
Maybe the problem of survuvalfly detecting that kbmaster is not supported can be solved by adjusting the size of kb in config?

**Comment by FallenCrystal** [comment]
this behavior goes beyond vanilla. it will never be supported.
only a minority of anti-cheat (or none at all) support this.
ncp did not repel the check. if survivalfly is flagged. the value you adjusted is too large.
`nocheatplus is all about letting players enforce the "vanilla mechanic"`

**Comment by AkariDream** [comment]
hint: GrimAC has a simulated motion engine that should support this kind of thing. even setback players wont notice. but this may also be incompatible. i dont recommend trying to modify knockback

**Comment by Lysandr0** [comment]
As @AkariDream correctly said, if it is something that does not follow vanilla Minecraft's mechanics, it won't be supported.
At least, not until we get more manpower to support these kind of things.

You could however, ask the developer to create a hook specifically for NCP.
