### ISSUE TITLE
Add a way too disable jesus check in survivalfly

### ISSUE THREAD

**Issue by compieter-gh** [Updated-NoCheatPlus/NoCheatPlus#27]
### Describe the features of this added check
i wanna use npc without the jesus check (anarchy server) and i found it in the source code where it is located but my lack of knowledge about java that is why i can't make it my self..

### Description of how this check would work
well a true or false option in the config by the survivalfly section.

### Any extra information about what should be added? (Config options...)
nope

**Comment by Lysandr0** [comment]
You can exempt players from getting checked for waterwalk cheats by giving them the following permission: `nocheatplus.checks.moving.survivalfly.waterwalk`.

**Comment by compieter-gh** [comment]
Thank you is there a list for all the checks somewhere?

**Comment by Lysandr0** [comment]
https://github.com/Lysandr0/Docs/tree/master/Settings/Checks

Hopefully it'll be merged soon enough with the old wiki, for now you can overview all checks from this page.

**Comment by compieter-gh** [comment]
yeah thank you very much
