### ISSUE TITLE
Flamepaper 1.8.8 NCP ERROR

### ISSUE THREAD

**Issue by rejomy** [Updated-NoCheatPlus/NoCheatPlus#271]
Ncp ver latest
Version Flamepaper 1.8.8
Protocol 4.6.0
https://paste.md-5.net/dosiqatali.bash

**Comment by ghost** [comment]
invalid issues, version ncp and other not showed

**Comment by rejomy** [comment]
> invalid issues, version ncp and other not showed

разрабу переай плз

**Comment by FL4ME1337** [comment]
> Ncp ver latest Version Flamepaper 1.8.8 Protocol 4.6.0 https://paste.md-5.net/dosiqatali.bash

Try update ProtocolLib to 4.8.0
