### ISSUE TITLE
Kick For Elytra

### ISSUE THREAD

**Issue by NCPUser** [Updated-NoCheatPlus/NoCheatPlus#273]
Im use 1.12.2 
And Latest Bulid
Im Use Fireworks So Many Me Kicked For Hacks Im No Use Hacks
![image](https://user-images.githubusercontent.com/86876065/209192501-163d07f5-4d1c-4777-b592-8203ddd086fb.png)

**Comment by NCPUser** [comment]
![image](https://user-images.githubusercontent.com/86876065/209193147-fc05e9a5-00d1-4289-9508-d9b281ae7f69.png)

**Comment by ghost** [comment]
needs plugin list + try disable strict for elytra check

**Comment by NCPUser** [comment]
What Strict?

**Comment by NCPUser** [comment]
Plugin List My Test Server.
![image](https://user-images.githubusercontent.com/86876065/209478073-da28a2b9-09e9-4de1-937b-bab426603816.png)
