### ISSUE TITLE
KBMaster

### ISSUE THREAD

**Issue by FengXiaoSkidGod** [Updated-NoCheatPlus/NoCheatPlus#278]
### Describe the features of this added check
       Support KBMaster
### Description of how this check would work
       When I add Plugius KnockBackMaster, I get flag with SurvivalFly
### Any extra information about what should be added? (Config options...)
       Support customer knockback

I guess you can fix this by adding some config

**Comment by nuym** [comment]
This should not be a problem fixed by NoCheatPlus, you should go to KnockBackMaster author to fix it , or write it yourself by nocheatplus addon
差不多得了，自己修去

**Comment by Lysandr0** [comment]
With the current state of things, we don't plan on supporting such plugins for the time being.
Not until we get enough manpower, at least.
