### ISSUE TITLE
Criticals 

### ISSUE THREAD

**Issue by ghost** [Updated-NoCheatPlus/NoCheatPlus#283]
blank first hits during critical hit on jump, how can i fix it ?

**Comment by Lysandr0** [comment]
Please follow the issue's template.
What's the added tag to the violation?

**Comment by ghost** [comment]
no tag, only blank hits

**Comment by Lysandr0** [comment]
Gonna need much more info than that. :)
I can't manage to get false positives with the Critical check by just jumping and hitting whilst falling.
