### ISSUE TITLE
Breaking packed mud flags player for fastbreak

### ISSUE THREAD

**Issue by USBCharger** [Updated-NoCheatPlus/NoCheatPlus#284]
#### *Complete* output of the `ncp version` command (please prefer text here)
15:42:04.009
[CHAT] git-Paper-346 ~MC: 1.19.3~
15:42:04.010
[CHAT] Detected: 1.19.3
15:42:04.010
[CHAT] NoCheatPlus:
15:42:04.010
[CHAT] Plugin: 3.17.1-SNAPSHOT-Updated-b153
15:42:04.010
[CHAT] MCAccess: 1.13-1.19|? / Bukkit-API
15:42:04.011
[CHAT] Features:
15:42:04.011
[CHAT] blocks: BlocksMC1_4, BlocksMC1_5, BlocksMC1_6_1, BlocksMC1_7_2, BlocksMC1_8, BlocksMC1_9, BlocksMC1_10, BlocksMC1_11, BlocksMC1_12, BlocksMC1_13, BlocksMC1_14, BlocksMC1_15, BlocksMC1_16, BlocksMC1_17, BlocksMC1_19, MCAccessBukkitModern
15:42:04.011
[CHAT] checks: FastConsume, Gutenberg, HotFixFallingBlockPortalEnter, AttackFrequency, FlyingFrequency, KeepAliveFrequency
15:42:04.011
[CHAT] defaults: pvpKnockBackVelocity
15:42:04.012
[CHAT] packet-listeners: UseEntityAdapter, MovingFlying, OutgoingPosition, KeepAliveAdapter, SoundDistance, WrongTurnAdapter, NoSlow, Fight
15:42:04.031
[CHAT] Hooks:
15:42:04.032
[CHAT] AllViolations~NCP~ 1.0, ViolationFrequency~NCP~ 1.0
15:42:04.033
[CHAT] »Related Plugins«
15:42:04.033
[CHAT] ProtocolLib v5.0.0-SNAPSHOT-b602, ViaVersion v4.5.1
#### Short description of the issue and how to reproduce (is it random / always happens / side conditions ?)
Breaking packed mud with any pickaxe flags you for fastbreak (after the first block)
#### Have you made any (noteworthy) changes to the default configuration of NCP?
Not that I can recall
#### Do you run any other special plugins that affect game mechanics next to NC+ (skills, machines, adding/changing blocks, other anti-cheating)?
Not that I can think of
#### Provide additional information: for bypasses, vulnerabilities and reproducible issues, we request a [debug log. ](https://github.com/Updated-NoCheatPlus/Docs/blob/master/Development/Debugging.md#on-the-fly-debug-output-for-individual-players) Use [GitHub gists](https://gist.github.com/) or [PasteBin](http://pastebin.com/) or similar for errors and huge logs, or attach a (zip-) file here.

Log file attached, player is GalacticRealms (my alt)
[nocheatplus.log](https://github.com/Updated-NoCheatPlus/NoCheatPlus/files/10808217/nocheatplus.log)

**Comment by Lysandr0** [comment]
Assume fixed with build 154
