### ISSUE TITLE
Add Hitbox Cheat Detection

### ISSUE THREAD

**Issue by EclipsesDev** [Updated-NoCheatPlus/NoCheatPlus#286]
### Describe the features of this added check
NCP will detect it and kick or ban the cheater

### Description of how this check would work
You probably know hitbox cheat.. basicly a cheat that allows player to expand enemy/other player hitbox, usually cheat client have this

### Any extra information about what should be added? (Config options...)
This check is kinda important since it doesn't get detected/canceled at all by nocheatplus

**Comment by Lysandr0** [comment]
Duplicate of #235
Technically, we already have an experimental HitBox check with the `bleeding-parts` branch, but the check is still missing a latency-compensation system, and we have to recode the entire speed handling first.
