### ISSUE TITLE
1.19.4: minecarts not firing PlayerMoveEvents

### ISSUE THREAD

**Issue by Imptovskii** [Updated-NoCheatPlus/NoCheatPlus#290]
#### *Complete* output of the `ncp version` command (please prefer text here)
```
> ncp version
[17:42:41 INFO]: »Version information«
[17:42:41 INFO]: Server:
[17:42:41 INFO]: git-Paper-470 ~MC: 1.19.4~
[17:42:41 INFO]: Detected: 1.19.4
[17:42:41 INFO]: NoCheatPlus:
[17:42:41 INFO]: Plugin: 3.17.1-SNAPSHOT-Updated-b155
[17:42:41 INFO]: MCAccess: 1.13-1.19|? / Bukkit-API
[17:42:41 INFO]: Features:
[17:42:41 INFO]: blocks: BlocksMC1_4, BlocksMC1_5, BlocksMC1_6_1, BlocksMC1_7_2, BlocksMC1_8, BlocksMC1_9, BlocksMC1_10, BlocksMC1_11, BlocksMC1_12, BlocksMC1_13, BlocksMC1_14, BlocksMC1_15, BlocksMC1_16, BlocksMC1_17, BlocksMC1_19, MCAccessBukkitModern
[17:42:41 INFO]: checks: FastConsume, Gutenberg, HotFixFallingBlockPortalEnter, FlyingFrequency, KeepAliveFrequency
[17:42:41 INFO]: defaults: pvpKnockBackVelocity
[17:42:41 INFO]: packet-listeners: MovingFlying, OutgoingPosition, KeepAliveAdapter, SoundDistance, Fight
[17:42:41 INFO]: Hooks:
AllViolations~NCP~ 1.0, ViolationFrequency~NCP~ 1.0
[17:42:41 INFO]: »Related Plugins«
[17:42:41 INFO]: ProtocolLib v5.0.0-SNAPSHOT-b618, ViaVersion v4.6.2
```

#### Short description of the issue and how to reproduce (is it random / always happens / side conditions ?)

Just ride minecart more than 1 chunk and leave minecart
https://www.youtube.com/watch?v=br94x4x40Xo

#### Have you made any (noteworthy) changes to the default configuration of NCP?
Default config

#### Do you run any other special plugins that affect game mechanics next to NC+ (skills, machines, adding/changing blocks, other anti-cheating)?
No

#### Provide additional information: for bypasses, vulnerabilities and reproducible issues, we request a [debug log. ](https://github.com/Updated-NoCheatPlus/Docs/blob/master/Development/Debugging.md#on-the-fly-debug-output-for-individual-players) Use [GitHub gists](https://gist.github.com/) or [PasteBin](http://pastebin.com/) or similar for errors and huge logs, or attach a (zip-) file here.

[nocheatplus.zip](https://github.com/Updated-NoCheatPlus/NoCheatPlus/files/11069166/nocheatplus.zip)

**Comment by molor** [comment]
Can confirm, just sit in minecart and ride ~10 blocks then press [Shift] and you will be kicked.
Logs:
```
[NoCheatPlus] Player failed CreativeFly: tried to move unexpectedly while in air; tags: EXTREME_MOVE; violations: 14527.
[NoCheatPlus] (CONSOLE) Kicked Player : Flying?
```

**Comment by Lysandr0** [comment]
(Ignore the commit reference, it was #288 not this one)
Currently, I cannot reproduce this on a 1.19.3 server. Need to test with .4 still.

**Comment by Imptovskii** [comment]
> (Ignore the commit reference, it was #288 not this one) Currently, I cannot reproduce this on a 1.19.3 server. Need to test with .4 still.

Same trouble:
https://youtu.be/F1A0e6Iga0E

**Comment by Lysandr0** [comment]
Was able to reproduce on 1.19.4.
Judging from the log and the first-hand testing, the player seemingly tries to cover with a single player move event the distance traveled with the minecart (from the mounting location to dismounting location).
Was not able to reproduce this with other vehicles (horses, boats ...).

Now, because this does not happen on 1.19.3, either Mojang or Spigot changed something regarding player/vehicle move when updating to 1.19.4... Will need some further checking.

**Comment by Imptovskii** [comment]
Well, the behavior has changed, now it doesn't kick, but just sets back to the original position
https://youtu.be/HxfxM4jVxOU
[nocheatplus.zip](https://github.com/Updated-NoCheatPlus/NoCheatPlus/files/11168466/nocheatplus.zip)

**Comment by xaw3ep** [comment]
It seems like the teleport comes from another plugin, the log showed TP PLUGIN, can you try again without NCP to see if the issue still happens?

**Comment by Imptovskii** [comment]
> It seems like the teleport comes from another plugin, the log showed TP PLUGIN, can you try again without NCP to see if the issue still happens?

I found the problem, it is related to the ClearLagg plugin (lol), i do not use this plugin to clear items, there are many other features there)

Issue fixed, sorry for a bit of misinformation

**Comment by Lysandr0** [comment]
I do wonder if it was intentional on Spigot's part to not fire player move events anymore while riding minecarts...
if not, it would explain why the server fires a player move event from mount to dismount location, which could yield a ridiculously huge move, depending on how far the minecart has travelled (which doesn't make much sense).

**Comment by Bobcat00** [comment]
Build 157 is working on my server. Thanks for this.

Maybe open an issue with Spigot regarding the player move events?

**Comment by Lysandr0** [comment]
> Build 157 is working on my server. Thanks for this.
> 
> Maybe open an issue with Spigot regarding the player move events?

Haven't checked Spigot's changes yet personally, but yeah, we should probably do, unless intended of course.

Will close this one. Do leave a note here for future follow-ups about it :)
