### ISSUE TITLE
1.20 support

### ISSUE THREAD

**Issue by ghost** [Updated-NoCheatPlus/NoCheatPlus#297]
[14:00:44 WARN]: [NoCheatPlus] The block data is incomplete:
--- Missing entries -------------------------------
* BLOCK BREAKING (SUSPICIOUS_GRAVEL / SOLID+GROUND)
* BLOCK BREAKING (PITCHER_PLANT / IGN_PASSABLE)
* BLOCK BREAKING (SNIFFER_EGG / SOLID+IGN_PASSABLE+GROUND)
* BLOCK BREAKING (CALIBRATED_SCULK_SENSOR / SOLID+IGN_PASSABLE+GROUND)
* BLOCK BREAKING (PITCHER_CROP / IGN_PASSABLE)

AND PLEASE UNBAN MISHA#5141, because discord fixed ip ban bypass.. i'm sorry @Lysandr0

**Comment by Lysandr0** [comment]
Done both. As long as you'll abide by the server's rules this time.

**Comment by ghost** [comment]
thanks
