### ISSUE TITLE
1.20,The Player cannot move

### ISSUE THREAD

**Issue by CatTeaA** [Updated-NoCheatPlus/NoCheatPlus#298]
NoCheatPlus Build#163    Profile defaul.
Player movement triggers"failed.MorePackets：sent too many moves"

**Comment by CatTeaA** [comment]
Original client（No Mod）

**Comment by Lysandr0** [comment]
Update to the latest build of Spigot which fixes the bug you're likely referring to. :)

**Comment by CatTeaA** [comment]
Perfect solution
