### ISSUE TITLE
Add GeyserMC support

### ISSUE THREAD

**Issue by compieter-gh** [Updated-NoCheatPlus/NoCheatPlus#30]
### Describe the features of this added check
Well when using NCP with Geyser it glitches out i can't walk at all
https://github.com/GeyserMC/Geyser There should be an API you will be able too use.
Hope this get's added.

### Description of how this check would work
Idk
### Any extra information about what should be added? (Config options...)
Nope

**Comment by Lysandr0** [comment]
Gonna drop this one here for anyone interested in it, since this ticket was upvoted quite a bit :p
https://github.com/Updated-NoCheatPlus/CompatNoCheatPlus

Just note that the hook is currently only for compatibility, it will not add any specific feature/check for bedrock players.

**Comment by compieter-gh** [comment]
@Lysandr0 Thank you very much.

**Comment by angushushu** [comment]
Hi there, a quick question: we are using geyser-bc, should we put cncp in the bc server or paper server(where ncp is located)?

**Comment by angushushu** [comment]
> @Lysandr0 Thank you very much.



> @Lysandr0 Thank you very much.

Hi there, a quick question: we are using geyser-bc, should we put cncp in the bc server or paper server(where ncp is located)?

**Comment by angushushu** [comment]
> @Lysandr0 Thank you very much.

Hi there, a quick question: we are using geyser-bc, should we put cncp in the bc server or paper server(where ncp is located)?
