### ISSUE TITLE
Editing a sign in 1.20 triggers AutoSign hack

### ISSUE THREAD

**Issue by EpicKnarvik97** [Updated-NoCheatPlus/NoCheatPlus#305]
#### *Complete* output of the `ncp version` command (please prefer text here)
Server 1
```
§c§l»Version information«§7
§6§lServer:§7
§7git-Paper-46 ~MC: 1.20.1~
§7§eDetected: §71.20.1
§6§lNoCheatPlus:§7
§7§ePlugin: §73.17.1-SNAPSHOT-Updated-b164
§7§eMCAccess: §71.13-1.19|? / Bukkit-API
§6§lFeatures:
§7§eblocks§7: BlocksMC1_4§f, §7BlocksMC1_5§f, §7BlocksMC1_6_1§f, §7BlocksMC1_7_2§f, §7BlocksMC1_8§f, §7BlocksMC1_9§f, §7BlocksMC1_10§f, §7BlocksMC1_11§f, §7BlocksMC1_12§f, §7BlocksMC1_13§f, §7BlocksMC1_14§f, §7BlocksMC1_15§f, §7BlocksMC1_16§f, §7BlocksMC1_17§f, §7BlocksMC1_19§f, §7BlocksMC1_20§f, §7MCAccessBukkitModern
§7§echecks§7: FastConsume§f, §7Gutenberg§f, §7HotFixFallingBlockPortalEnter§f, §7AttackFrequency§f, §7FlyingFrequency§f, §7KeepAliveFrequency
§7§edefaults§7: pvpKnockBackVelocity
§7§epacket-listeners§7: UseEntityAdapter§f, §7MovingFlying§f, §7OutgoingPosition§f, §7KeepAliveAdapter§f, §7SoundDistance§f, §7WrongTurnAdapter§f, §7NoSlow§f, §7Fight
§6§lHooks:
§7AllViolations~NCP~ 1.0§f, §7Citizens2~cncp~ 2.0§f, §7mcMMO~cncp~ 2.3§f, §7ViolationFrequency~NCP~ 1.0
§c§l»Related Plugins«§7
§7CompatNoCheatPlus v6.6.7-SNAPSHOT-b10§f, §7ProtocolLib v5.1.0-SNAPSHOT-654
```

Server 2
```
§c§l»Version information«§7
§6§lServer:§7
§7git-Paper-46 ~MC: 1.20.1~
§7§eDetected: §71.20.1
§6§lNoCheatPlus:§7
§7§ePlugin: §73.17.1-SNAPSHOT-Updated-b164
§7§eMCAccess: §71.13-1.19|? / Bukkit-API
§6§lFeatures:
§7§eblocks§7: BlocksMC1_4§f, §7BlocksMC1_5§f, §7BlocksMC1_6_1§f, §7BlocksMC1_7_2§f, §7BlocksMC1_8§f, §7BlocksMC1_9§f, §7BlocksMC1_10§f, §7BlocksMC1_11§f, §7BlocksMC1_12§f, §7BlocksMC1_13§f, §7BlocksMC1_14§f, §7BlocksMC1_15§f, §7BlocksMC1_16§f, §7BlocksMC1_17§f, §7BlocksMC1_19§f, §7BlocksMC1_20§f, §7MCAccessBukkitModern
§7§echecks§7: FastConsume§f, §7Gutenberg§f, §7HotFixFallingBlockPortalEnter
§7§edefaults§7: pvpKnockBackVelocity
§6§lHooks:
§7AllViolations~NCP~ 1.0§f, §7ViolationFrequency~NCP~ 1.0
§c§l»Related Plugins«§7
§7CompatNoCheatPlus v6.6.7-SNAPSHOT-b10
```

#### Short description of the issue and how to reproduce (is it random / always happens / side conditions ?)
Whenever a sign is edited by right-clicking, and the sign hasn't been recently placed (if the server has been restarted after it was placed), it triggers `[NC+] EpicKnarvik97 failed AutoSign: tried to use the autosign hack (Subcheck: block_mismatch) (VL20)`

#### Have you made any (noteworthy) changes to the default configuration of NCP?
I haven't changed anything.

#### Do you run any other special plugins that affect game mechanics next to NC+ (skills, machines, adding/changing blocks, other anti-cheating)?
Server1 has several that might be relevant, but for Server2, Geyser+Floodgate is all that might affect it (this was all tested on the Java client, not a Bedrock client).

#### Provide additional information: for bypasses, vulnerabilities and reproducible issues, we request a [debug log. ](https://github.com/Updated-NoCheatPlus/Docs/blob/master/Development/Debugging.md#on-the-fly-debug-output-for-individual-players) Use [GitHub gists](https://gist.github.com/) or [PasteBin](http://pastebin.com/) or similar for errors and huge logs, or attach a (zip-) file here.
23-06-24 13:54:15 [INFO] EpicKnarvik97 failed AutoSign: tried to use the autosign hack (Subcheck: block_mismatch) (VL10)
23-06-24 13:58:04 [INFO] EpicKnarvik97 failed AutoSign: tried to use the autosign hack (Subcheck: block_mismatch) (VL20)
23-06-24 13:58:23 [INFO] EpicKnarvik97 failed AutoSign: tried to use the autosign hack (Subcheck: block_mismatch) (VL30)
23-06-24 13:58:37 [INFO] EpicKnarvik97 failed AutoSign: tried to use the autosign hack (Subcheck: block_mismatch) (VL40)

**Comment by Lysandr0** [comment]
Assuming fixed. Do leave a note if not.

**Comment by EpicKnarvik97** [comment]
There are still some problems. If a sign is broken, AutoSign triggers on sign editing for all signs again, except for the most recently placed sign if placed after the other sign was broken.

**Comment by Bobcat00** [comment]
I just tried Paper 1.20.1-62 and NCP build 165 and I can't edit signs. It fails autosign, subcheck block_mismatch.
I have skipempty set to true.

**Comment by EpicKnarvik97** [comment]
I just found out that hanging signs that hang outwards from a wall (as opposed to hanging in a roof or a chain) cannot be used at all without triggering the AutoSign hack. Simply placing it down triggers AutoSign after the player sets the sign text.
