### ISSUE TITLE
False positives for Survival Fly Checks on Bedrock

### ISSUE THREAD

**Issue by JHarris12345** [Updated-NoCheatPlus/NoCheatPlus#311]
#### *Complete* output of the `ncp version` command (please prefer text here)
https://gyazo.com/e02c10fe561730edf966e2d7931fb117
#### Short description of the issue and how to reproduce (is it random / always happens / side conditions ?)
Bedrock players get flagged for Survival fly a lot and get kicked for "Moved unexpectedly". I believe this occurs when a player is standing on a chest. Is there a way to disable checks for bedrock players or increase support for it?
#### Have you made any (noteworthy) changes to the default configuration of NCP?
Just disabled a bunch of checks. Changed nothing else
#### Do you run any other special plugins that affect game mechanics next to NC+ (skills, machines, adding/changing blocks, other anti-cheating)?
Vulcan

**Comment by JHarris12345** [comment]
I disabled kicking from the check but it still glitches bedrock players back every time they try to jump on a block. It's very glitchy

**Comment by Lysandr0** [comment]
You'll need to run NoCheatPlus along with CompatNoCheatPlus: https://github.com/Updated-NoCheatPlus/CompatNoCheatPlus
Support is currently bare-bone: it just exempts bedrock players on join.

Fully-fledged checks are planned, though we cannot really give an ETA due to the lack of manpower.

**Comment by JHarris12345** [comment]
What I did as a temporary fix was make a fork where each check has a bedrock: true/false boolean and I can individually exempt bedrock players from checks

**Comment by Lysandr0** [comment]
There's no need of such a workaround with CNCP. Is the hook not working?

**Comment by JHarris12345** [comment]
CNCP disables for all bedrock players. My one lets me disable only the checks causing me issues

**Comment by Lysandr0** [comment]
The same thing can be achieved with CNCP, you'll just need to specify which check you want to exempt bedrock players from in the config file.

**Comment by JHarris12345** [comment]
> The same thing can be achieved with CNCP, you'll just need to specify which check you want to exempt bedrock players from in the config file.

Just letting you know that the default config is broken as it says bedrock-extempt-checks not bedrock-exempt-checks

**Comment by SkyDude0** [comment]
> The same thing can be achieved with CNCP, you'll just need to specify which check you want to exempt bedrock players from in the config file.

i try with CNCP but seems that dosent exclude bedrock player
