### ISSUE TITLE
[False positive] Jump near a lectern

### ISSUE THREAD

**Issue by Momonche** [Updated-NoCheatPlus/NoCheatPlus#32]
### Full output of /ncp version
---- Version information ----
#### Server ####
git-Purpur-606 ~MC: 1.15.2~
detected: 1.15.2
#### NoCheatPlus ####
Plugin: 3.17-SNAPSHOT-b1153-CustomFork
MCAccess: 1.13.2-1.15|? / Bukkit-API
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | MCAccessBukkitModern
checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
defaults: pvpKnockBackVelocity
packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight
Hooks: AllViolations~NCP~ 1.0 | ViolationFrequency~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v4.5.1 | ViaVersion v3.0.2-SNAPSHOT | ProtocolSupport v4.29-dev

### Describe the issue
When a player jump near a lectern, he get a rollback

### How to reproduce the issue
Place a Lectern, jump near it

### Extra links/Videos (Including debug logs)
[NC+] MissClick failed SurvivalFly: tried to perform an illegal move (Subchecks: vdistrel+lowjump) (VL857)

**Comment by MarkElf** [comment]
Walking on this specific ledges of the lantern highlighted in red results in setback. Both variants are affected since they both use the same model.
https://cdn.discordapp.com/attachments/603221572890656807/735833205805940756/unknown.png

**Comment by Lysandr0** [comment]
This should be fixed with build 108. Lectern among other blocks have been re-defined.
Edit: can confirm. This is fixed.
