### ISSUE TITLE
Lilypad glitch since 1.20.4

### ISSUE THREAD

**Issue by Geitenijs** [Updated-NoCheatPlus/NoCheatPlus#333]
#### *Complete* output of the `ncp version` command (please prefer text here)
Server:
git-Paper-397 ~MC: 1.20.4~
Detected: 1.20.4
NoCheatPlus:
Plugin: 3.17.1-SNAPSHOT-Updated-b186
MCAccess: 1.13-1.20|? / Bukkit-API
Features:
blocks: BlocksMC1_4, BlocksMC1_5, BlocksMC1_6_1, BlocksMC1_7_2, BlocksMC1_8, BlocksMC1_9, BlocksMC1_10, BlocksMC1_11, BlocksMC1_12, BlocksMC1_13, BlocksMC1_14, BlocksMC1_15, BlocksMC1_16, BlocksMC1_17, BlocksMC1_19, BlocksMC1_20, MCAccessBukkitModern
checks: FastConsume, Gutenberg, HotFixFallingBlockPortalEnter, AttackFrequency, FlyingFrequency, KeepAliveFrequency
defaults: pvpKnockBackVelocity
packet-listeners: UseEntityAdapter, MovingFlying, OutgoingPosition, KeepAliveAdapter, SoundDistance, WrongTurnAdapter, NoSlow, Fight
Hooks:
AllViolations~NCP~ 1.0, DoubleJump 1.0.0, ViolationFrequency~NCP~ 1.0
»Related Plugins«
CompatNoCheatPlus v6.6.7-SNAPSHOT-b10, ProtocolLib v5.2.0-SNAPSHOT-679, ViaVersion v4.9.2

#### Short description of the issue and how to reproduce (is it random / always happens / side conditions ?)
When moving against a lily pad in 1.20.4, NCP is pulling me back and showing "failed Passable". This was not the case on 1.20.2

#### Have you made any (noteworthy) changes to the default configuration of NCP?
No

#### Do you run any other special plugins that affect game mechanics next to NC+ (skills, machines, adding/changing blocks, other anti-cheating)?
No

#### Provide additional information: for bypasses, vulnerabilities and reproducible issues, we request a [debug log. ](https://github.com/Updated-NoCheatPlus/Docs/blob/master/Development/Debugging.md#on-the-fly-debug-output-for-individual-players) Use [GitHub gists](https://gist.github.com/) or [PasteBin](http://pastebin.com/) or similar for errors and huge logs, or attach a (zip-) file here.

https://github.com/Updated-NoCheatPlus/NoCheatPlus/assets/40541903/21c1b62e-a822-4753-af32-f41ed5567e4b

**Comment by TW527E** [comment]
We had the same problem.
