### ISSUE TITLE
This plugin has caused us a lot of trouble

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [Updated-NoCheatPlus/NoCheatPlus#359]
![image](https://github.com/Updated-NoCheatPlus/NoCheatPlus/assets/141799770/fb09298d-eb64-4442-8427-b7fa626a1b8e)

![image](https://github.com/Updated-NoCheatPlus/NoCheatPlus/assets/141799770/350f453d-13f5-4a34-a98b-469bd5c853b7)

Some players have reported that as long as they keep digging blocks, they will be kicked out, or they need to click twice to dig them out

**Comment by Brokkonaut** [comment]
You can disable those checks in the config if they cause issues on your server. For a real bug report you should follow the bug report template.

**Comment by MinecraftEarthVillage** [comment]
> 如果这些检查导致服务器出现问题，您可以在配置中禁用这些检查。对于真正的错误报告，您应该遵循错误报告模板。

我后来尝试其它类似插件，还是决定——不安装“反作弊”，因为我们MOD服务器的性质···
