### ISSUE TITLE
Survivalfly: leaving a waterfall (2)

### ISSUE THREAD

**Issue by Lysandr0** [Updated-NoCheatPlus/NoCheatPlus#5]
### Full output of /ncp version
```
[INFO] ---- Version information ----

[INFO] #### Server ####

[INFO] git-Spigot-2040c4c-77fd87e ~MC: 1.15.2~

[INFO] detected: 1.15.2

[INFO] #### NoCheatPlus ####

[INFO] Plugin: 3.17-SNAPSHOT-b1153-CustomFork

[INFO] MCAccess: 1.13.2-1.15|? / Bukkit-API

[INFO] Features:

[INFO] blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | MCAccessBukkitModern

[INFO] checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency

[INFO] defaults: pvpKnockBackVelocity

[INFO] packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight

[INFO] Hooks: AllViolations~NCP~ 1.0 | ViolationFrequency~NCP~ 1.0

[INFO] #### Related Plugins ####

[INFO] ProtocolLib v4.5.0 | ProtocolSupport v4.29-dev
```

### Describe the issue
Issue n.#3 seems to not have been fully fixed, although this time it's _much_ harder to reproduce it.

### Extra links/Videos (Including debug logs)
[nocheatplus (1).log](https://github.com/Updated-NoCheatPlus/NoCheatPlus/files/4567267/nocheatplus.1.log)

https://www.dropbox.com/s/btbvdlbgne31ut6/waterfall.mov?dl=0
### Any possible config options changed or plugins that may cause interference?
Default config.

**Comment by CaptainObvious0** [comment]
I'll tag/assign @xaw3ep since they have a better sense of what this check is doing than I do. Although I was unable to reproduce this issue, from the debug logs it seems like the same issue as last time.

**Comment by Lysandr0** [comment]
Seems fixed with the latest build(s). Will reopen this ticket in case it shows up again.
