### ISSUE TITLE
Setting BoatsAnywhere no longer works

### ISSUE THREAD

**Issue by MarkElf** [Updated-NoCheatPlus/NoCheatPlus#53]
### Full output of /ncp version
[INFO] ---- Version information ----
[INFO] #### Server ####
[INFO] git-Spigot-9639cf7-c3a22e7 MC: 1.16.1
[INFO] detected: 1.16.1
[INFO] #### NoCheatPlus ####
[INFO] Plugin: 3.17-SNAPSHOT-Updated-b62
[INFO] MCAccess: 1.13-1.16|? / Bukkit-API
[INFO] Features:
[INFO] blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | BlocksMC1_16 | MCAccessBukkitModern
[INFO] checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[INFO] defaults: pvpKnockBackVelocity
[INFO] packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight
[INFO] Hooks: AllViolationsNCP 1.0 | ViolationFrequencyNCP 1.0
[INFO] #### Related Plugins ####
[INFO] ProtocolLib v4.6.0 | ProtocolSupport v4.29-dev
### Describe the issue
The setting 'boatanywhere' does not allow for boats to be placed on the ground. Providing a player with 'nocheatplus.checks.blockplace.boats' allows them to be placed on land.
### How to reproduce the issue
Place a boat on the ground is prevented.
### Extra links/Videos (Including debug logs)
n/a
### Any possible config options changed or plugins that may cause interference?
n/a

**Comment by CaptainObvious0** [comment]
Isn't this config option doing what is intended? Depending on the setting it will only allow for boats to be placed on water, which is what is what the config option enforces. Not sure the reason behind it but whats the issue here?

**Comment by MarkElf** [comment]
I wrote the issue ticket based on another user's feedback without testing 'false' - which does seem to let boats be placed anywhere. I guess now I mean that 'boatsanywhere: false' allows boats to be placed on land while 'true' doesn't let boats be placed on land. It's inverted. Not really a big deal.

**Comment by MarkElf** [comment]
Not too relevant, just going to close.
