### ISSUE TITLE
Fast Break issue

### ISSUE THREAD

**Issue by FallenEmo** [Updated-NoCheatPlus/NoCheatPlus#55]
### Full output of /ncp version: 05.08 16:13:37 [Server] Server thread/INFO ProtocolLib v4.6.0-SNAPSHOT-b473
05.08 16:13:37 [Server] Server thread/INFO #### Related Plugins ####
05.08 16:13:37 [Server] Server thread/INFO Hooks: AllViolations~NCP~ 1.0 | MyPet 1.1 | ViolationFrequency~NCP~ 1.0
05.08 16:13:37 [Server] Server thread/INFO packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight
05.08 16:13:37 [Server] Server thread/INFO defaults: pvpKnockBackVelocity
05.08 16:13:37 [Server] Server thread/INFO checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
05.08 16:13:37 [Server] Server thread/INFO blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | BlocksMC1_16 | MCAccessBukkitModern
05.08 16:13:37 [Server] Server thread/INFO Features:
05.08 16:13:37 [Server] Server thread/INFO MCAccess: 1.13-1.16|? / Bukkit-API
05.08 16:13:37 [Server] Server thread/INFO Plugin: 3.17-SNAPSHOT-Updated-b62
05.08 16:13:37 [Server] Server thread/INFO #### NoCheatPlus ####
05.08 16:13:37 [Server] Server thread/INFO detected: 1.16.1
05.08 16:13:37 [Server] Server thread/INFO git-Spigot-9639cf7-8fb6585 ~MC: 1.16.1~
05.08 16:13:37 [Server] Server thread/INFO #### Server ####
05.08 16:13:37 [Server] Server thread/INFO ---- Version information ----

**Comment by MarkElf** [comment]
setBlock(BridgeMaterial.PISTON, new BlockProps(woodPickaxe, 1.5f, secToMs(2.25, 1.15, 0.6, 0.4, 0.3, 0.25, 0.2)));
        setBlock(BridgeMaterial.STICKY_PISTON, new BlockProps(woodPickaxe, 1.5f, secToMs(2.25, 1.15, 0.6, 0.4, 0.3, 0.25, 0.2)));

 to BlockPropertires. Piston mining times were never really defined and mining them with eff enchant was only recently discovered to be a bug.

Edit: Only 1.16.x defined additional block mine times so it's exclusive to 1.16.x.

**Comment by MarkElf** [comment]
This was fixed a few builds ago.
