### ISSUE TITLE
Creativefly: false positive on glide/no glide transition phases.

### ISSUE THREAD

**Issue by Lysandr0** [Updated-NoCheatPlus/NoCheatPlus#59]
### Full output of /ncp version
```
[INFO] ---- Version information ----

[INFO] #### Server ####

[INFO] git-Spigot-9639cf7-4b9bc9d ~MC: 1.16.1~

[INFO] detected: 1.16.1

[INFO] #### NoCheatPlus ####

[INFO] Plugin: 3.17-SNAPSHOT-Updated-b65

[INFO] MCAccess: 1.13-1.16|? / Bukkit-API

[INFO] Features:

[INFO] blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | BlocksMC1_16 | MCAccessBukkitModern

[INFO] checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency

[INFO] defaults: pvpKnockBackVelocity

[INFO] packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight

[INFO] Hooks: AllViolations~NCP~ 1.0 | ViolationFrequency~NCP~ 1.0

[INFO] #### Related Plugins ####

[INFO] ProtocolLib v4.6.0-SNAPSHOT-b472 | ProtocolSupport v4.29-dev
```
### Describe the issue
Toggling between gliding phases will result in a Cf false positive.
### How to reproduce the issue
While in creative, try to take off from the ground with an elytra. Also works if you toggle glide in air. Gliding in Survival is fine otherwise.
### Extra links/Videos (Including debug logs)
[nocheatplus.log](https://github.com/Updated-NoCheatPlus/NoCheatPlus/files/5058441/nocheatplus.log)
https://www.dropbox.com/s/8uxjoqvqv5lfoy6/ncptest.mov?dl=0
### Any possible config options changed or plugins that may cause interference?
Default config.

**Comment by Lysandr0** [comment]
Fixed with build n.67

**Comment by Lysandr0** [comment]
Upon further testing, this one seems to persist at least partially (toggle gliding in air is fixed, on ground is still buggy, especially if you repeatedly spam the space bar)

_Relevant videos:_
https://www.dropbox.com/s/fxnmo2s3etdg1ss/elytratest2.mov?dl=0 (Do note that I'm not spamming the space bar here, just jumping at intervals)
Mark's test: https://youtu.be/SZ55jVJvMiA (spam-jumping)
Log: https://pastebin.com/b2bTDkr8

**Comment by MarkElf** [comment]
This seems okay. After jumping around and spamming spacebar for 10+ minutes, I was setback 3-4 times. It's still possible to false it but it's extremely difficult unless you're intentionally trying to false it as I was. I wouldn't worry about it much.
This should be two instances: https://pastebin.com/rsjUL22U | https://pastebin.com/3U49xJxi

**Comment by Lysandr0** [comment]
I do believe those leftovers false positives boil down to vanilla bug(s), possibly another case of client and server being out of sync with each other(?). Perhaps we could add a gliding grace period thingy to cut all remaining FPs down.

I'll leave it open for the time being, in case Xaw3ep wants to review this issue further. :p
