### ISSUE TITLE
player walk on bed, skull, flower pod, redstone comparator/repeater

### ISSUE THREAD

**Issue by german-code** [Updated-NoCheatPlus/NoCheatPlus#61]
### Full output of /ncp version

> #### Server ####
git-PaperSpigot-"4c7641d" ~MC: 1.8.8~
  detected: 1.8.8
#### NoCheatPlus ####
Plugin: 3.17-SNAPSHOT-Updated-b67
MCAccess: 1.6.1-1.14.4|? / Bukkit-API
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | MCAccessBukkit
  checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
  defaults: pvpKnockBackVelocity
  packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | CatchAllAdapter | NoSlow | Fight
Hooks: AllViolations~NCP~ 1.0 | ViolationFrequency~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v4.5.1 | ViaVersion v3.0.1

### Describe the issue
The player set setbacked, when walking on  bed, skull, flower pod, redstone comparator/repeater

### How to reproduce the issue
walk over it on a 1.8.8 server with client version 1.8.9

### Extra links/Videos (Including debug logs)
Video: https://streamable.com/ku14r8
Debug log: https://pastebin.com/hmtr4Mu7
### Any possible config options changed or plugins that may cause interference?
Plugins:
- Protocollib
- ViaVersion
Config:
- Latest Autokick on GitHub

**Comment by xaw3ep** [comment]
Update to the latest build please!

**Comment by german-code** [comment]
fixed! thx!
