### ISSUE TITLE
End portal creation: triggers bdirection

### ISSUE THREAD

**Issue by ghost** [Updated-NoCheatPlus/NoCheatPlus#63]
### Full output of /ncp version
https://hastebin.com/eruvotukuk.md

### Describe the issue
Placing the last eye of ender to activate an end portal is causing bdirection error, preventing completion of the portal.

### How to reproduce the issue
Try to place the final eye of ender in our situation. (see link below)

### Extra links/Videos (Including debug logs)
https://cldup.com/i5VNeVdusi.jpg

### Any possible config options changed or plugins that may cause interference?
bdirection configuration: https://hastebin.com/eyebomibod.css

**Comment by Lysandr0** [comment]
Is this one still an issue?
Block shapes were refined just recently.
