### ISSUE TITLE
[FP] Passable

### ISSUE THREAD

**Issue by johndoe1Johndoe** [Updated-NoCheatPlus/NoCheatPlus#65]
### Full output of /ncp version
https://i.imgur.com/9l1yRro.png
### Describe the issue
check vid
### How to reproduce the issue
check vid
### Extra links/Videos (Including debug logs)
https://youtu.be/Qw91o9-ic7Y
https://hastebin.com/gazukidaxa
### Any possible config options changed or plugins that may cause interference?
dunno

**Comment by MarkElf** [comment]
I fixed this in February and it wasn't moved over to Updated-NCP ever. Simple fix: https://github.com/MarkElf/NoCheatPlus/commit/8aa9ef8ab568d09f02d13488c243c220c5b4891e
