### ISSUE TITLE
[FP] Passable

### ISSUE THREAD

**Issue by johndoe1Johndoe** [Updated-NoCheatPlus/NoCheatPlus#66]
### Full output of /ncp version
https://i.imgur.com/9l1yRro.png
### Describe the issue
happens only with non colored glass panels
### How to reproduce the issue
check vid
### Extra links/Videos (Including debug logs)
https://youtu.be/CxG_ssYCk0A
https://hastebin.com/gayojivena
### Any possible config options changed or plugins that may cause interference?
dunno

**Comment by MarkElf** [comment]
Also, an easy fix that was never pulled to the main branch: https://github.com/MarkElf/NoCheatPlus/commit/e044c85450ba120b9298585bb20b4926a4ba3579

**Comment by CaptainObvious0** [comment]
Video was removed, issue created is no longer valid
