### ISSUE TITLE
[FP] Creativefly

### ISSUE THREAD

**Issue by johndoe1Johndoe** [Updated-NoCheatPlus/NoCheatPlus#67]
### Full output of /ncp version
https://i.imgur.com/9l1yRro.png
### Describe the issue
check vid
### How to reproduce the issue
check vid
### Extra links/Videos (Including debug logs)
https://youtu.be/ewdjlBGH8Nw
https://hastebin.com/riyeyucijo
### Any possible config options changed or plugins that may cause interference?
dunno

**Comment by CaptainObvious0** [comment]
Video removed. Empathizes the point to include information about reproducing the issue in text.
