### ISSUE TITLE
Elytra gliding with slowfall effect freezes the player

### ISSUE THREAD

**Issue by MarkElf** [Updated-NoCheatPlus/NoCheatPlus#69]
### Full output of /ncp version
---- Version information ----
#### Server ####
git-Paper-135 ~MC: 1.16.1~
detected: 1.16.1
#### NoCheatPlus ####
Plugin: 3.17-SNAPSHOT-Updated-b69
MCAccess: 1.13-1.16|? / Bukkit-API
Features:
blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | BlocksMC1_16 | MCAccessBukkitModern
checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter
defaults: pvpKnockBackVelocity
Hooks: AllViolations~NCP~ 1.0 | ViolationFrequency~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v4.6.0
### Describe the issue
The player model flickers and freeze when changing pitch (To an extreme, let's say a 180 degree turn) while gliding with an elytra, debug log seems to think it's a new jumpphase (jumpphase: 0)
### How to reproduce the issue
Equit an elytra, /effect give playername minecraft:slow_falling 60 3, and glide while moving the mouse around (Again, let's say a 180 dress turn as that triggers it pretty instantly).
### Extra links/Videos (Including debug logs)
https://youtu.be/5gg3SZEw7iQ
### Any possible config options changed or plugins that may cause interference?
None.

**Comment by Lysandr0** [comment]
I this one still relevant?
The elytra model was corrected quite a few times in the past. Might be superseded.

**Comment by MarkElf** [comment]
Gonna assume it was fixed as well.
