### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ghost** [Updated-NoCheatPlus/NoCheatPlus#78]
Add more KillAura checks or improve them
Add teleport function: When the staff click on the message report, the plugin teleport the staff that click to him

**Comment by CaptainObvious0** [comment]
NoCheatPlus will enforce what it can, while KillAura is not really doing outside of what a normal player could do (yes, I understand its still a cheat). The only way to detect KillAura would be through some sort of rotation check which validates the players rotation are possible from a vanilla client. If those rotation checks were to be made public, it would be very easy for client developers to make rotations around it thus making it pointless to make the check.

Sort sort of update to alerts isn't a bad idea, but the point of this fork is providing compatibility for newer versions. Something I'll keep in mind for the future but it's unlikely this will be done anytime soon.
