### ISSUE TITLE
False positives with world borders (vanilla)

### ISSUE THREAD

**Issue by ghost** [Updated-NoCheatPlus/NoCheatPlus#79]
### Full output of /ncp version
![image](https://user-images.githubusercontent.com/43325908/97786062-b23fe980-1b87-11eb-8698-3caeef41b9b8.png)

### Describe the issue
When someone pass the force field, and got teleport to the spawn, the anticheat flag a log

### How to reproduce the issue
Set a force field, and set the force field to close, when get you and you get teleport to some place, ncp will flage

**Comment by MarkElf** [comment]
Can you provide a debug log, /ncp debug player (playername)?
