### ISSUE TITLE
NCP error

### ISSUE THREAD

**Issue by ghost** [Updated-NoCheatPlus/NoCheatPlus#82]

**Comment by Lysandr0** [comment]
1) You're using a really outdated build. Grab the latest from [here](https://ci.codemc.io/job/Updated-NoCheatPlus/job/Updated-NoCheatPlus/85/) 
2) You don't seem to have ProtocolLib installed, which you should download https://www.spigotmc.org/resources/protocollib.1997/

**Comment by Magzypotato** [comment]
> 1. You're using a really outdated build. Grab the latest from [here](https://ci.codemc.io/job/Updated-NoCheatPlus/job/Updated-NoCheatPlus/85/)
> 2. You don't seem to have ProtocolLib installed, which you should download https://www.spigotmc.org/resources/protocollib.1997/

It worked now with no errors 👍
