### ISSUE TITLE
Error when people joins

### ISSUE THREAD

**Issue by ghost** [Updated-NoCheatPlus/NoCheatPlus#85]
### Full output of /ncp version
https://paste.gg/p/anonymous/c027bce413b64ed8a0ac798b957413a1

### Describe the issue
Everytime a player joins this message appear in that backendserver console. I have bungeecord btw.
https://paste.gg/p/anonymous/72378185e97c49309a31fbe05f59a8e8

**Comment by compieter-gh** [comment]
Have the same issue.

**Comment by mibby** [comment]
Likewise.
https://paste.gg/p/anonymous/cc342893a4b542deb1dd49e613fe5ad6/files/9873ce7a69374d60a65e59f6938a14c7/raw

Compiled as of commit https://github.com/Updated-NoCheatPlus/NoCheatPlus/commit/2b5820cd19666f994ce33dd4ca2a4929cfd507cf with both PR manually pulled.

**Comment by CaptainObvious0** [comment]
Please update ProtocolLib as it's the source of the error. Looking through the history it seems 489 fixed this.
