### ISSUE TITLE
Random Error in Console

### ISSUE THREAD

**Issue by ghost** [Updated-NoCheatPlus/NoCheatPlus#86]
Short description of the issue. I see this error in console randomly. Not sure what may be the cause. Only started once I went from PaperMC 1.16.3 to PaperMC 1.16.4

Complete output of the ncp version command (please prefer text here).
Using this version: https://ci.codemc.io/job/Updated-NoCheatPlus/job/Updated-NoCheatPlus/85/

How to reproduce the issue (is it random / always happens / side conditions)? Random occurrence in console
Have you made any (noteworthy) changes to the default configuration of NCP? No changes

Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)? Nothing

https://pastebin.com/nG9fFHyk

**Comment by ghost** [comment]
20-12-12 16:38:27 [INFO] ---- Version information ----
#### Server ####
git-Paper-323 ~MC: 1.16.4~
  detected: 1.16.4
#### NoCheatPlus ####
Plugin: 3.17-SNAPSHOT-Updated-b81
MCAccess: 1.13-1.16|? / Bukkit-API
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12 | BlocksMC1_13 | BlocksMC1_14 | BlocksMC1_15 | BlocksMC1_16 | MCAccessBukkitModern
  checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency
  defaults: pvpKnockBackVelocity
  packet-listeners: UseEntityAdapter | SoundDistance | WrongTurnAdapter | NoSlow | Fight
Hooks: AllViolations~NCP~ 1.0 | Citizens2~cncp~ 2.0 | mcMMO~cncp~ 2.3 | MyPet 1.1 | ViolationFrequency~NCP~ 1.0
#### Related Plugins ####
CompatNoCheatPlus v6.6.6-SNAPSHOT-sMD5NET-b91 | ProtocolLib v4.6.0-SNAPSHOT-b480
20-12-12 18:00:05 [SEVERE] IDisableListener (fr.neatmonster.nocheatplus.players.PlayerDataManager): NoClassDefFoundError / fr/neatmonster/nocheatplus/components/registry/factory/RichFactoryRegistry$CheckRemovalSpec
20-12-12 18:00:05 [SEVERE] java.lang.NoClassDefFoundError: fr/neatmonster/nocheatplus/components/registry/factory/RichFactoryRegistry$CheckRemovalSpec
	fr.neatmonster.nocheatplus.players.PlayerDataManager.clearData(PlayerDataManager.java:999)
	fr.neatmonster.nocheatplus.players.PlayerDataManager.onDisable(PlayerDataManager.java:548)
	fr.neatmonster.nocheatplus.NoCheatPlus.onDisable(NoCheatPlus.java:696)
	org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
	org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415)
	org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516)
	org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502)
	org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495)
	org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:435)
	net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:770)
	net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:704)
	net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1044)
	net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
	java.lang.Thread.run(Thread.java:748)

**Comment by CaptainObvious0** [comment]
Please update to the latest build of ProtocolLib for 1.16 as I see you're running 480 while the latest version is 492
