### ISSUE TITLE
AntiSpam

### ISSUE THREAD

**Issue by JacobF-dev** [Updated-NoCheatPlus/NoCheatPlus#95]
Quick question:
How can I disable the antispam for the chat? Which value do I have to modify?
It is unneeded in my server.

**Comment by Lysandr0** [comment]
Disable the [Chat.Text](https://github.com/Updated-NoCheatPlus/Docs/blob/master/Settings/Checks/%5BChat%5D-Text.md) and [Chat.Commands](https://github.com/Updated-NoCheatPlus/Docs/blob/master/Settings/Checks/%5BChat%5D-Commands.md) checks.
