### ISSUE TITLE
Survivalfly Setback when having Blindness

### ISSUE THREAD

**Issue by JuliCarles** [Updated-NoCheatPlus/NoCheatPlus#96]
### Full output of /ncp version
b86 (latest)

### Describe the issue
Our plugin applies Slowness + Blindness effect when entering a certain area. If players are sprinting when this happens and try to continue to do so, they get setbacks and can climb from 240 to over 2000 violations if they continue to sprint for a few seconds.

### How to reproduce the issue
Sprint to a certain area and use /effect to apply the BLINDNESS effect (this is the one causing the issue). If you are sprinting at the time you get the effect, you should get a setback. 

This does not happen if you are walking at the time you get the effect, only if you are running. The blindness effect will then prevent you from running any further (vanilla), but the setbacks do happen anyway.

### Extra links/Videos (Including debug logs)

https://user-images.githubusercontent.com/15850628/106639557-d682dc00-6563-11eb-885e-953776116e26.mp4

### Any possible config options changed or plugins that may cause interference?
Default configuration.

**Comment by JuliCarles** [comment]
Update:

This isn't sprinting while being blind (as vanilla does not allow that) but rather that second between sprinting and getting the effect that causes the violation level to increase and setback for a second.

It's a pretty big deal in our server as it break the gamemode completely. Thanks.

**Comment by Lysandr0** [comment]
The blindsprint has been removed for now.
Apparently the client ignores the effect if it's already sprinting (the server won't allow the player to sprint in the next sprint phase however).
Don't think simply cancelling the toggleSprint event if blind would work, since the client is authoritative over the sprint status...

Edit: Actually a potential workaround to this would be to 'refresh' the player's food level (get the level, store it, set it to 0 to reset sprint, then restore it back)

**Comment by yorik100** [comment]
> 
> 
> The blindsprint has been removed for now.
> Apparently the client ignores the effect if it's already sprinting (the server won't allow the player to sprint in the next sprint phase however).
> Don't think simply cancelling the toggleSprint event if blind would work, since the client is authoritative over the sprint status...
> 
> Edit: Actually a potential workaround to this would be to 'refresh' the player's food level (get the level, store it, set it to 0 to reset sprint, then restore it back)

Just check if the player stopped and started sprinting again while blinded?

**Comment by Lysandr0** [comment]
Problem is that with the current implementation players are assumed to be sprinting all the time. You'd need to get the last time the player was standing still, rather.

**Comment by yorik100** [comment]
> Problem is that with the current implementation players are assumed to be sprinting all the time. You'd need to get the last time the player was standing still, rather.

That would not work properly as hitting a player, boat or a minecart breaks your sprint, colliding with a wall also breaks your sprint
